/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Banda;

import modelo.Banda;
import services.Sql.Banda.Sql_banda;
import configuracion.ConstantesMensajes;
import excepciones.Excepciones;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class Banda_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Datos_Actualizar
     */
    public Banda_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLBL = new javax.swing.JLabel();
        bandaLBL = new javax.swing.JLabel();
        tiempoLBL = new javax.swing.JLabel();
        origenLBL = new javax.swing.JLabel();
        generoLBL = new javax.swing.JLabel();
        codigoTXT = new javax.swing.JTextField();
        nombreTXT = new javax.swing.JTextField();
        actuadosTXT = new javax.swing.JTextField();
        origenTXT = new javax.swing.JTextField();
        generoTXT = new javax.swing.JTextField();
        actualizarBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoLBL.setText("Introduce el codigo de la banda");

        bandaLBL.setText("Nombre de la banda");

        tiempoLBL.setText("Años actuados");

        origenLBL.setText("Lugar de origen");

        generoLBL.setText("Genero");

        codigoTXT.setText("-1");

        nombreTXT.setText("Banda");

        actuadosTXT.setText("1960-actualidad");
        actuadosTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actuadosTXTActionPerformed(evt);
            }
        });

        origenTXT.setText("Origen");

        generoTXT.setText("Genero");

        actualizarBTN.setText("Actualizar");
        actualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoLBL)
                    .addComponent(generoLBL)
                    .addComponent(origenLBL)
                    .addComponent(tiempoLBL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(volverBTN)
                        .addComponent(bandaLBL)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actuadosTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origenTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actualizarBTN)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLBL)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandaLBL)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiempoLBL)
                    .addComponent(actuadosTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origenLBL)
                    .addComponent(origenTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoLBL)
                    .addComponent(generoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN)
                    .addComponent(actualizarBTN))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBTNActionPerformed
        try {

            // Obtención de datos del formulario
            String codigoStr = codigoTXT.getText().trim();
            String nombre = nombreTXT.getText().trim();
            String origen = origenTXT.getText().trim();
            String genero = generoTXT.getText().trim();
            String actuados = actuadosTXT.getText().trim();

            // Validación del código
            // El código no puede estar vacío
            if (codigoStr.isEmpty()) {
                throw new Excepciones("Ingrese el codigo de la banda.");
            }

            // El código debe ser numérico
            if (!codigoStr.matches("\\d+")) {
                throw new Excepciones("El codigo de la banda debe ser numerico.");
            }

            int codigo = Integer.parseInt(codigoStr);

            // El código no puede ser negativo
            if (codigo < 0) {
                throw new Excepciones("El codigo no puede ser negativo.");
            }

            // Validación: comprobar si la banda existe antes de consultar
            if (!utils.Util_Clases.existeBandaCodigo(codigo)) {
                throw new Excepciones("No existe la banda con ese código");
            }

            // Validación del nombre
            // El nombre no puede estar vacío ni contener el texto por defecto
            if (nombre.isEmpty() || nombre.equalsIgnoreCase("Banda")) {
                throw new Excepciones("Ingrese un nombre valido.");
            }

            // Validación del origen
            // El origen no puede estar vacío ni contener el texto por defecto
            if (origen.isEmpty() || origen.equalsIgnoreCase("Origen")) {
                throw new Excepciones("Ingrese un origen valido.");
            }

            // Validación del género
            // El género no puede estar vacío ni contener el texto por defecto
            if (genero.isEmpty() || genero.equalsIgnoreCase("Genero")) {
                throw new Excepciones("Ingrese un genero valido.");
            }

            // Validación de actuación
            // La actuación no puede estar vacía ni contener el texto por defecto
            if (actuados.isEmpty() || actuados.equalsIgnoreCase("1111-actualidad")) {
                throw new Excepciones("Ingrese una actuacion valida.");
            }

            // Ejemplo: "1980-actualidad" o "1980-2020"
            String[] partes = actuados.split("-");

            if (partes.length != 2) {
                throw new Excepciones("Formato de actuación inválido. Use: 1960-actualidad");
            }

            int anioInicio;
            int anioFin;

            // Validación del año inicio
            try {
                anioInicio = Integer.parseInt(partes[0].trim());
            } catch (Exception e) {
                throw new Excepciones("El año de inicio no es válido.");
            }

            // Validación del año fin
            if (partes[1].trim().equalsIgnoreCase("actualidad")) {
                anioFin = LocalDate.now().getYear();
            } else {
                try {
                    anioFin = Integer.parseInt(partes[1].trim());
                } catch (Exception e) {
                    throw new Excepciones("El año final no es válido.");
                }
            }

            // Validación lógica
            if (anioFin < anioInicio) {
                throw new Excepciones("El año final no puede ser menor que el año inicial.");
            }

            // Cálculo de años de actividad
            int aniosActuacion = anioFin - anioInicio;

            // VAlidación maxima
            if (aniosActuacion > 80) {
                throw new Excepciones("La banda no puede superar los 80 años de actuación.");
            }

            // Creación del objeto Banda
            Banda banda = new Banda(
                    nombre,
                    actuados,
                    origen,
                    genero
            );

            // Actualización en base de datos
            Sql_banda.update(banda, codigo);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(
                    null,
                    "Banda actualizada correctamente"
            );

        } catch (NumberFormatException e) {

            // Error cuando el código no es numérico
            JOptionPane.showMessageDialog(
                    null,
                    ConstantesMensajes.codigoInvalido
            );

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error inesperado: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_actualizarBTNActionPerformed

    private void actuadosTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actuadosTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actuadosTXTActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banda_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banda_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banda_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banda_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banda_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actuadosTXT;
    private javax.swing.JButton actualizarBTN;
    private javax.swing.JLabel bandaLBL;
    private javax.swing.JLabel codigoLBL;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JLabel generoLBL;
    private javax.swing.JTextField generoTXT;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JLabel origenLBL;
    private javax.swing.JTextField origenTXT;
    private javax.swing.JLabel tiempoLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
