/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import swing.Album.Album_Actualizar;
import swing.Banda.Banda_Actualizar;
import swing.Cancion.Cancion_Actualizar;
import swing.Musico.Musico_Actualizar;

/**
 *
 * @author isard
 */
public class Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        bandaBTN = new javax.swing.JButton();
        albumBTN = new javax.swing.JButton();
        MusicoBTN = new javax.swing.JButton();
        cancionBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Selecciona una tabla");

        bandaBTN.setText("Banda");
        bandaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaBTNActionPerformed(evt);
            }
        });

        albumBTN.setText("Album");
        albumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumBTNActionPerformed(evt);
            }
        });

        MusicoBTN.setText("Musico");
        MusicoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicoBTNActionPerformed(evt);
            }
        });

        cancionBTN.setText("Cancion");
        cancionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionLBL)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(volverBTN)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bandaBTN)
                                .addComponent(MusicoBTN)
                                .addComponent(cancionBTN)
                                .addComponent(albumBTN)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(opcionLBL)
                .addGap(18, 18, 18)
                .addComponent(bandaBTN)
                .addGap(18, 18, 18)
                .addComponent(MusicoBTN)
                .addGap(18, 18, 18)
                .addComponent(albumBTN)
                .addGap(18, 18, 18)
                .addComponent(cancionBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaBTNActionPerformed
        // Se crea una instancia de la ventana Banda_Actualizar.
        Banda_Actualizar act = new Banda_Actualizar();
        act.setVisible(true);

    }//GEN-LAST:event_bandaBTNActionPerformed

    private void MusicoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicoBTNActionPerformed
        // Se crea una instancia de la ventana Musico_Actualizar.
        Musico_Actualizar ma = new Musico_Actualizar();
        ma.setVisible(true);

    }//GEN-LAST:event_MusicoBTNActionPerformed

    private void albumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumBTNActionPerformed
        // Se crea una instancia de la ventana Album_Actualizar.
        Album_Actualizar aa = new Album_Actualizar();
        aa.setVisible(true);
    }//GEN-LAST:event_albumBTNActionPerformed

    private void cancionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionBTNActionPerformed
        // Se crea una instancia de la ventana Cancion_Actualizar.
        Cancion_Actualizar ca = new Cancion_Actualizar();
        ca.setVisible(true);
    }//GEN-LAST:event_cancionBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);

    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MusicoBTN;
    private javax.swing.JButton albumBTN;
    private javax.swing.JButton bandaBTN;
    private javax.swing.JButton cancionBTN;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
