/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import swing.Album.Album_MostrarCodigo;
import swing.Banda.Banda_MostrarCodigo;
import swing.Cancion.Cancion_MostrarCodigo;
import swing.Musico.Musico_MostrarCodigo;

/**
 *
 * @author isard
 */
public class ConsultarPorCodigo extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarCodigo
     */
    public ConsultarPorCodigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        bandaBTN = new javax.swing.JButton();
        musicoBTN = new javax.swing.JButton();
        albumBTN = new javax.swing.JButton();
        cancionBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Selecciona la tabla");

        bandaBTN.setText("Banda");
        bandaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaBTNActionPerformed(evt);
            }
        });

        musicoBTN.setText("Musico");
        musicoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicoBTNActionPerformed(evt);
            }
        });

        albumBTN.setText("Album");
        albumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumBTNActionPerformed(evt);
            }
        });

        cancionBTN.setText("Cancion");
        cancionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(opcionLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicoBTN)
                            .addComponent(bandaBTN)
                            .addComponent(albumBTN)
                            .addComponent(cancionBTN)
                            .addComponent(volverBTN))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(opcionLBL)
                .addGap(18, 18, 18)
                .addComponent(bandaBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicoBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(albumBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancionBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaBTNActionPerformed
        // Se crea una instancia de la ventana Banda_ConsultarPorCodigo.
        Banda_MostrarCodigo codigo = new Banda_MostrarCodigo();
        codigo.setVisible(true);
    }//GEN-LAST:event_bandaBTNActionPerformed

    private void albumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumBTNActionPerformed
        // Se crea una instancia de la ventana Album_ConsultarPorCodigo.
        Album_MostrarCodigo amc = new Album_MostrarCodigo();
        amc.setVisible(true);
    }//GEN-LAST:event_albumBTNActionPerformed

    private void cancionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionBTNActionPerformed
        // Se crea una instancia de la ventana Album_ConsultarPorCodigo.
        Cancion_MostrarCodigo cmc = new Cancion_MostrarCodigo();
        cmc.setVisible(true);
    }//GEN-LAST:event_cancionBTNActionPerformed

    private void musicoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicoBTNActionPerformed
        // Se crea una instancia de la ventana Musico_ConsultarPorCodigo.
        Musico_MostrarCodigo mmc = new Musico_MostrarCodigo();
        mmc.setVisible(true);
    }//GEN-LAST:event_musicoBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarPorCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarPorCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton albumBTN;
    private javax.swing.JButton bandaBTN;
    private javax.swing.JButton cancionBTN;
    private javax.swing.JButton musicoBTN;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
