/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import swing.Album.Album_Mostrar;
import swing.Banda.Banda_Mostrar;
import swing.Cancion.Cancion_Mostrar;
import swing.Musico.Musico_Mostrar;

/**
 *
 * @author isard
 */
public class ConsultaCompleta extends javax.swing.JFrame {

    /**
     * Creates new form Visualizar
     */
    public ConsultaCompleta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        bandaBTN = new javax.swing.JButton();
        musicoBTN = new javax.swing.JButton();
        albumBTN = new javax.swing.JButton();
        cancionBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Selecciona una tabla");

        bandaBTN.setText("Banda");
        bandaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaBTNActionPerformed(evt);
            }
        });

        musicoBTN.setText("Musico");
        musicoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicoBTNActionPerformed(evt);
            }
        });

        albumBTN.setText("Album");
        albumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumBTNActionPerformed(evt);
            }
        });

        cancionBTN.setText("Cancion");
        cancionBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionLBL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(albumBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(musicoBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bandaBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volverBTN)
                            .addComponent(cancionBTN))
                        .addGap(15, 15, 15)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(opcionLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bandaBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicoBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(albumBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancionBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaBTNActionPerformed
        // Se crea una instancia de la ventana Banda_ConsultaCompleta.
        Banda_Mostrar mostrar = new Banda_Mostrar();
        mostrar.setVisible(true);
    }//GEN-LAST:event_bandaBTNActionPerformed

    private void musicoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicoBTNActionPerformed
        // Se crea una instancia de la ventana Musico_ConsultaCompleta.
        Musico_Mostrar mm = new Musico_Mostrar();
        mm.setVisible(true);
    }//GEN-LAST:event_musicoBTNActionPerformed

    private void albumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumBTNActionPerformed
        // Se crea una instancia de la ventana Album_ConsultaCompleta.
        Album_Mostrar am = new Album_Mostrar();
        am.setVisible(true);
    }//GEN-LAST:event_albumBTNActionPerformed

    private void cancionBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionBTNActionPerformed
        // Se crea una instancia de la ventana Cancion_ConsultaCompleta.
        Cancion_Mostrar cm = new Cancion_Mostrar();
        cm.setVisible(true);
    }//GEN-LAST:event_cancionBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCompleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton albumBTN;
    private javax.swing.JButton bandaBTN;
    private javax.swing.JButton cancionBTN;
    private javax.swing.JButton musicoBTN;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
