/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import services.Sql.Sql_Multitabla;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isard
 */
public class Ejercicios_Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicios_Consultas
     */
    public Ejercicios_Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejercicionCBX = new javax.swing.JComboBox<>();
        textoLBL = new javax.swing.JLabel();
        consultarBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultaTBL = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejercicionCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        textoLBL.setText("Selecciona un ejercicio");

        consultarBTN.setText("Consultar");
        consultarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        consultaTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "nombre", "lugar de origen", "Titulos albumes", "numero canciones"
            }
        ));
        jScrollPane1.setViewportView(consultaTBL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(textoLBL)
                        .addGap(55, 55, 55)
                        .addComponent(ejercicionCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(volverBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultarBTN)
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ejercicionCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultarBTN)
                    .addComponent(volverBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);

    }//GEN-LAST:event_volverBTNActionPerformed

    private void consultarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBTNActionPerformed
        int opcion = Integer.parseInt(ejercicionCBX.getSelectedItem().toString());

        try {

            switch (opcion) {

                case 1 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"Nombre", "lugar de origen", "titulos_albumes", "numero_canciones"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio1();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 4) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1],
                                matrizMostrar[i][2],
                                matrizMostrar[i][3]
                            });
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 1: " + e.getMessage());
                    }
                }

                case 2 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"Nombre", "instrumento", "titulo_album", "canciones en album"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio2();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 4) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1],
                                matrizMostrar[i][2],
                                matrizMostrar[i][3]
                            });
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 2: " + e.getMessage());
                    }
                }

                case 3 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                // ❌ Antes había 4 columnas
                                // ✅ Ahora solo 3
                                new String[]{
                                    "anio_publicacion",
                                    "titulo_album",
                                    "titulo_cancion"
                                }
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio3();

                        for (int i = 0; i < matrizMostrar.length; i++) {

                            if (matrizMostrar[i] == null
                                    || matrizMostrar[i].length < 3) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1],
                                matrizMostrar[i][2]
                            });
                        }

                    } catch (Excepciones e) {

                        throw new Excepciones(
                                "Error en ejercicio 3: "
                                + e.getMessage()
                        );
                    }
                }

                case 4 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"Compositor", "titulo_cancion", "titulo_album"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio4();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 3) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1],
                                matrizMostrar[i][2]
                            });
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 4: " + e.getMessage());
                    }
                }

                case 5 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"Nombre", "albumes_publicados"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio5();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 2) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1]
                            });
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 5: " + e.getMessage());
                    }
                }

                case 6 -> {
                    try {

                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                              
                                new String[]{
                                    "titulo_album",
                                    "canciones_en_album",
                                    "autor",
                                    "banda_o_musico"
                                }
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio6();

                        for (int i = 0; i < matrizMostrar.length; i++) {

                            if (matrizMostrar[i] == null
                                    || matrizMostrar[i].length < 4) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1],
                                matrizMostrar[i][2],
                                matrizMostrar[i][3]
                            });
                        }

                    } catch (Excepciones e) {

                        throw new Excepciones(
                                "Error en ejercicio 6: "
                                + e.getMessage()
                        );
                    }
                }

                case 7 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"Nombre_banda"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio7();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 1) {
                                continue;
                            }

                            modelo.addRow(new Object[]{matrizMostrar[i][0]});
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 7: " + e.getMessage());
                    }
                }

                case 8 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"titulo_album", "duracion_media"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio8();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 2) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1]
                            });
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 8: " + e.getMessage());
                    }
                }

                case 9 -> {
                    try {
                        DefaultTableModel modelo = new DefaultTableModel(
                                new Object[][]{},
                                new String[]{"Nombre", "nacionalidad", "instrumento"}
                        );

                        consultaTBL.setModel(modelo);

                        String[][] matrizMostrar = Sql_Multitabla.ejercicio9();

                        for (int i = 0; i < matrizMostrar.length; i++) {
                            if (matrizMostrar[i] == null || matrizMostrar[i].length < 3) {
                                continue;
                            }

                            modelo.addRow(new Object[]{
                                matrizMostrar[i][0],
                                matrizMostrar[i][1],
                                matrizMostrar[i][2]
                            });
                        }

                    } catch (Excepciones e) {
                        throw new Excepciones("Error en ejercicio 9: " + e.getMessage());
                    }
                }
            }

        } catch (Excepciones e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error general: " + e.getMessage());
        }
    }//GEN-LAST:event_consultarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicios_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicios_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicios_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicios_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicios_Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable consultaTBL;
    private javax.swing.JButton consultarBTN;
    private javax.swing.JComboBox<String> ejercicionCBX;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
