/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import swing.Album.Album_Borrar;
import swing.Banda.Banda_Borrar;
import swing.Cancion.Cancion_Borrar;
import swing.Musico.Musico_Borrar;

/**
 *
 * @author isard
 */
public class Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        bandaTXT = new javax.swing.JButton();
        musicoTXT = new javax.swing.JButton();
        albumTXT = new javax.swing.JButton();
        cancionTXT = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Selecciona una tabla");

        bandaTXT.setText("Banda");
        bandaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaTXTActionPerformed(evt);
            }
        });

        musicoTXT.setText("Musico");
        musicoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicoTXTActionPerformed(evt);
            }
        });

        albumTXT.setText("Album");
        albumTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumTXTActionPerformed(evt);
            }
        });

        cancionTXT.setText("Cancion");
        cancionTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancionTXTActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(opcionLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicoTXT)
                            .addComponent(bandaTXT)
                            .addComponent(albumTXT)
                            .addComponent(cancionTXT)
                            .addComponent(volverBTN))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionLBL)
                .addGap(18, 18, 18)
                .addComponent(bandaTXT)
                .addGap(18, 18, 18)
                .addComponent(musicoTXT)
                .addGap(18, 18, 18)
                .addComponent(albumTXT)
                .addGap(18, 18, 18)
                .addComponent(cancionTXT)
                .addGap(18, 18, 18)
                .addComponent(volverBTN)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bandaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaTXTActionPerformed
        // Se crea una instancia de la ventana Banda_Eliminar.
        Banda_Borrar delete = new Banda_Borrar();
        delete.setVisible(true);
    }//GEN-LAST:event_bandaTXTActionPerformed

    private void musicoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicoTXTActionPerformed
        // Se crea una instancia de la ventana Album_Eliminar.
        Musico_Borrar mb = new Musico_Borrar();
        mb.setVisible(true);

    }//GEN-LAST:event_musicoTXTActionPerformed

    private void albumTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumTXTActionPerformed
        // Se crea una instancia de la ventana Musico_Eliminar.
        Album_Borrar ab = new Album_Borrar();
        ab.setVisible(true);
    }//GEN-LAST:event_albumTXTActionPerformed

    private void cancionTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancionTXTActionPerformed
        // Se crea una instancia de la ventana CAncion_Eliminar.
        Cancion_Borrar cb = new Cancion_Borrar();
        cb.setVisible(true);
    }//GEN-LAST:event_cancionTXTActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton albumTXT;
    private javax.swing.JButton bandaTXT;
    private javax.swing.JButton cancionTXT;
    private javax.swing.JButton musicoTXT;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
