/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import services.Sql.Album.Sql_Album;
import services.Sql.Banda.Sql_banda;
import services.Sql.Cancion.Sql_Cancion;
import services.Sql.Musico.Sql_Musico;
import services.ficheros.exportar.Exportar_Album;
import services.ficheros.exportar.Exportar_Banda;
import services.ficheros.exportar.Exportar_Cancion;
import services.ficheros.exportar.Exportar_Musico;
import excepciones.Excepciones;

/**
 *
 * @author isard
 */
public class OpcionExportar extends javax.swing.JFrame {

    /**
     * Creates new form OpcionExportar
     */
    public OpcionExportar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        volverBTN = new javax.swing.JButton();
        exportarBTN = new javax.swing.JButton();
        tablaCMB = new javax.swing.JComboBox<>();
        formatoCMB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Elige una opcion de tabla y formato para exportar");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        exportarBTN.setText("Exportar");
        exportarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarBTNActionPerformed(evt);
            }
        });

        tablaCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda", "Musico", "Album", "Cancion" }));

        formatoCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Json", "TXT", "Binario", "CSV" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(opcionLBL)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tablaCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formatoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverBTN)
                        .addGap(73, 73, 73)
                        .addComponent(exportarBTN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(opcionLBL)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablaCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN)
                    .addComponent(exportarBTN))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    private void exportarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarBTNActionPerformed
        // Se obtiene la tabla seleccionada del JComboBox.
        String tabla = tablaCMB.getSelectedItem().toString();

// Se obtiene el formato seleccionado del JComboBox.
        String formato = formatoCMB.getSelectedItem().toString();

// Se crea la opción combinando tabla y formato.
        String opcion = tabla + "_" + formato;

        try {

            // Matriz donde se almacenarán los datos consultados.
            String[][] datos;

            // Estructura switch para determinar qué exportación realizar.
            switch (opcion) {

                // =========================
                // OPCIONES BANDA
                // =========================
                case "Banda_TXT" -> {

                    // Consultar todos los datos de Banda.
                    datos = Sql_banda.consultarTabla();

                    // Exportar los datos a TXT.
                    Exportar_Banda.exportarTXT(datos);
                }

                case "Banda_CSV" -> {

                    // Consultar todos los datos de Banda.
                    datos = Sql_banda.consultarTabla();

                    // Exportar los datos a CSV.
                    Exportar_Banda.exportarCSV(datos);
                }

                case "Banda_Binario" -> {

                    // Consultar todos los datos de Banda.
                    datos = Sql_banda.consultarTabla();

                    // Exportar los datos a archivo binario.
                    Exportar_Banda.exportarBinario(datos);
                }

                case "Banda_Json" -> {

                    // Consultar todos los datos de Banda.
                    datos = Sql_banda.consultarTabla();

                    // Exportar los datos a JSON.
                    Exportar_Banda.exportarJSON(datos);
                }

                // =========================
                // OPCIONES MUSICO
                // =========================
                case "Musico_TXT" -> {

                    // Consultar todos los datos de Musico.
                    datos = Sql_Musico.consultarTabla();

                    // Exportar los datos a TXT.
                    Exportar_Musico.exportarTXT(datos);
                }

                case "Musico_CSV" -> {

                    // Consultar todos los datos de Musico.
                    datos = Sql_Musico.consultarTabla();

                    // Exportar los datos a CSV.
                    Exportar_Musico.exportarCSV(datos);
                }

                case "Musico_Binario" -> {

                    // Consultar todos los datos de Musico.
                    datos = Sql_Musico.consultarTabla();

                    // Exportar los datos a binario.
                    Exportar_Musico.exportarBinario(datos);
                }

                case "Musico_Json" -> {

                    // Consultar todos los datos de Musico.
                    datos = Sql_Musico.consultarTabla();

                    // Exportar los datos a JSON.
                    Exportar_Musico.exportarJSON(datos);
                }

                // =========================
                // OPCIONES ALBUM
                // =========================
                case "Album_TXT" -> {

                    // Consultar todos los datos de Album.
                    datos = Sql_Album.consultarTabla();

                    // Exportar los datos a TXT.
                    Exportar_Album.exportarTXT(datos);
                }

                case "Album_CSV" -> {

                    // Consultar todos los datos de Album.
                    datos = Sql_Album.consultarTabla();

                    // Exportar los datos a CSV.
                    Exportar_Album.exportarCSV(datos);
                }

                case "Album_Binario" -> {

                    // Consultar todos los datos de Album.
                    datos = Sql_Album.consultarTabla();

                    // Exportar los datos a binario.
                    Exportar_Album.exportarBinario(datos);
                }

                case "Album_Json" -> {

                    // Consultar todos los datos de Album.
                    datos = Sql_Album.consultarTabla();

                    // Exportar los datos a JSON.
                    Exportar_Album.exportarJSON(datos);
                }

                // =========================
                // OPCIONES CANCION
                // =========================
                case "Cancion_TXT" -> {

                    // Consultar todos los datos de Cancion.
                    datos = Sql_Cancion.consultarTabla();

                    // Exportar los datos a TXT.
                    Exportar_Cancion.exportarTXT(datos);
                }

                case "Cancion_CSV" -> {

                    // Consultar todos los datos de Cancion.
                    datos = Sql_Cancion.consultarTabla();

                    // Exportar los datos a CSV.
                    Exportar_Cancion.exportarCSV(datos);
                }

                case "Cancion_Binario" -> {

                    // Consultar todos los datos de Cancion.
                    datos = Sql_Cancion.consultarTabla();

                    // Exportar los datos a binario.
                    Exportar_Cancion.exportarBinario(datos);
                }

                case "Cancion_Json" -> {

                    // Consultar todos los datos de Cancion.
                    datos = Sql_Cancion.consultarTabla();

                    // Exportar los datos a JSON.
                    Exportar_Cancion.exportarJSON(datos);
                }

                // Opción inválida.
                default -> {

                    throw new Excepciones("Opcion no valida.");
                }
            }

        } catch (Excepciones e) {

            // Mostrar errores personalizados.
            System.out.println(e.getMessage());

        } catch (Exception e) {

            // Captura de errores inesperados.
            System.out.println("Error : " + e.getMessage());

            // Mostrar trazado del error.
            e.printStackTrace();
        }
    }//GEN-LAST:event_exportarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionExportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionExportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionExportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionExportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionExportar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportarBTN;
    private javax.swing.JComboBox<String> formatoCMB;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JComboBox<String> tablaCMB;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
