/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

/**
 *
 * @author isard
 */
public class TipoConsulta extends javax.swing.JFrame {

    /**
     * Creates new form MostrarCodigo
     */
    public TipoConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        VisualizarBTN = new javax.swing.JButton();
        VisualizarCodigoBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();
        consultasBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Selecciona tipo de consulta");

        VisualizarBTN.setText("Consulta completa");
        VisualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarBTNActionPerformed(evt);
            }
        });

        VisualizarCodigoBTN.setText("Consulta por codigo");
        VisualizarCodigoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarCodigoBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        consultasBTN.setText("Ejercicios Consultas");
        consultasBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultasBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VisualizarBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(opcionLBL))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(VisualizarCodigoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(consultasBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(volverBTN))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(opcionLBL)
                .addGap(18, 18, 18)
                .addComponent(VisualizarBTN)
                .addGap(12, 12, 12)
                .addComponent(VisualizarCodigoBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultasBTN)
                .addGap(18, 18, 18)
                .addComponent(volverBTN)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarBTNActionPerformed
        // Se crea una instancia de la ventana ConsultaCompleta.
        ConsultaCompleta visualizar = new ConsultaCompleta();
        visualizar.setVisible(true);
    }//GEN-LAST:event_VisualizarBTNActionPerformed

    private void VisualizarCodigoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarCodigoBTNActionPerformed
        // Se crea una instancia de la ventana ConsultarPorCodigo.
        ConsultarPorCodigo vc = new ConsultarPorCodigo();
        vc.setVisible(true);

    }//GEN-LAST:event_VisualizarCodigoBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    private void consultasBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultasBTNActionPerformed
        // Se crea una instancia de la ventana Ejercicios_consultas.
        Ejercicios_Consultas ex = new Ejercicios_Consultas();
        ex.setVisible(true);
    }//GEN-LAST:event_consultasBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VisualizarBTN;
    private javax.swing.JButton VisualizarCodigoBTN;
    private javax.swing.JButton consultasBTN;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
