package swing.Musico;

import modelo.Musico;
import services.Sql.Musico.Sql_Musico;
import configuracion.ConstantesMensajes;
import excepciones.Excepciones;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class Musico_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Musico_Actualizar
     */
    public Musico_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualizarBTN = new javax.swing.JButton();
        codBandaLBL = new javax.swing.JLabel();
        nombreLBL = new javax.swing.JLabel();
        fechaLBL = new javax.swing.JLabel();
        residenciaLBL = new javax.swing.JLabel();
        nacionLBL = new javax.swing.JLabel();
        instrumentoLBL = new javax.swing.JLabel();
        codigoLBL = new javax.swing.JLabel();
        codBandaTXT = new javax.swing.JTextField();
        nombreTXT = new javax.swing.JTextField();
        fechaTXT = new javax.swing.JTextField();
        residenciaTXT = new javax.swing.JTextField();
        nacionTXT = new javax.swing.JTextField();
        intrumentoTXT = new javax.swing.JTextField();
        codigoActTXT = new javax.swing.JTextField();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actualizarBTN.setText("Actualizar");
        actualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBTNActionPerformed(evt);
            }
        });

        codBandaLBL.setText("Codigo_banda");

        nombreLBL.setText("Nombre");

        fechaLBL.setText("Fecha de nacimiento");

        residenciaLBL.setText("Residencia");

        nacionLBL.setText("Nacionalidad");

        instrumentoLBL.setText("Instrumento");

        codigoLBL.setText("Codigo");

        codBandaTXT.setText("-1");

        nombreTXT.setText("Nombre");

        fechaTXT.setText("YYYY/MM/DD");
        fechaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaTXTActionPerformed(evt);
            }
        });

        residenciaTXT.setText("Residencia");
        residenciaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residenciaTXTActionPerformed(evt);
            }
        });

        nacionTXT.setText("Nacionalidad");

        intrumentoTXT.setText("Instrumento");

        codigoActTXT.setText("-1");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codBandaLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fechaLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(residenciaLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(residenciaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(codigoActTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nacionLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nacionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(instrumentoLBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(intrumentoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(volverBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(actualizarBTN)))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBandaLBL)
                    .addComponent(codBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residenciaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(residenciaLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacionLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intrumentoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instrumentoLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoLBL)
                    .addComponent(codigoActTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarBTN)
                    .addComponent(volverBTN))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaTXTActionPerformed

    private void residenciaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residenciaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residenciaTXTActionPerformed

    private void actualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBTNActionPerformed
        try {

            // Obtención de datos del formulario
            String codBandaStr = codBandaTXT.getText().trim();
            String codigoActStr = codigoActTXT.getText().trim();
            String nombre = nombreTXT.getText().trim();
            String fecha = fechaTXT.getText().trim();
            String residencia = residenciaTXT.getText().trim();
            String nacion = nacionTXT.getText().trim();
            String instrumento = intrumentoTXT.getText().trim();

            // Validación del código de banda
            // Variable nullable
            Integer codBanda = null;

            // Si el campo no está vacío se valida
            if (!codBandaStr.isEmpty()) {

                // El código debe ser numérico
                if (!codBandaStr.matches("-?\\d+")) {
                    throw new Excepciones("El codigo de la banda debe ser numerico.");
                }

                codBanda = Integer.parseInt(codBandaStr);

                // El código no puede ser negativo
                if (codBanda < 0) {
                    throw new Excepciones("El codigo no puede ser negativo.");
                }

                // Comprobación de existencia de la banda
                if (!utils.Util_Clases.existeBandaCodigo(codBanda)) {
                    JOptionPane.showMessageDialog(null, "No existe una banda con ese codigo.");
                    return;
                }
            }

            // Validación del código del músico
            // El código del músico no puede estar vacío
            if (codigoActStr.isEmpty()) {
                throw new Excepciones("Ingrese el codigo del musico.");
            }

            // El código del músico debe ser numérico
            if (!codigoActStr.matches("\\d+")) {
                throw new Excepciones("El codigo del musico debe ser numerico.");
            }

            int codigoAct = Integer.parseInt(codigoActStr);

            // El código no puede ser negativo
            if (codigoAct < 0) {
                throw new Excepciones("El codigo del musico no puede ser negativo.");
            }

            // Verificación de existencia del músico
            if (!utils.Util_Clases.existeMusicoPorCodigo(codigoAct)) {

                JOptionPane.showMessageDialog(null, "No existe un músico con ese código");
                return;
            }

            // Verificación de existencia de la Banda
            if (!utils.Util_Clases.existeBandaCodigo(codBanda)) {

                JOptionPane.showMessageDialog(null, "No existe un músico con ese código");
                return;
            }

            // Validación del nombre
            // El nombre no puede estar vacío ni contener el texto por defecto
            if (nombre.isEmpty() || nombre.equalsIgnoreCase("Nombre")) {
                throw new Excepciones("Ingrese un nombre valido.");
            }

            // Validación de la fecha
            // La fecha no puede estar vacía ni contener el texto por defecto
            if (fecha.isEmpty() || fecha.equalsIgnoreCase("YYYY/M/D")) {
                throw new Excepciones("Ingrese una fecha valida.");
            }

            // Validación flexible del formato de fecha
            // Permite fechas como:
            // 2000/1/1
            // 2000/01/01
            // 2000/12/5
            if (!fecha.matches("\\d{4}/\\d{1,2}/\\d{1,2}")) {
                throw new Excepciones("La fecha debe tener formato YYYY/M/D.");
            }

            // Conversión de fecha
            // Se define el formato esperado
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy/M/d");

            LocalDate fechaNacimiento;

            try {

                // Conversión de String a LocalDate
                fechaNacimiento = LocalDate.parse(fecha, formato);

            } catch (Exception ex) {

                JOptionPane.showMessageDialog(
                        null,
                        "La fecha introducida no es valida."
                );
                return;
            }

            // Validación de residencia
            // La residencia no puede estar vacía ni contener el texto por defecto
            if (residencia.isEmpty() || residencia.equalsIgnoreCase("Residencia")) {
                throw new Excepciones("Ingrese una residencia valida.");
            }

            // Validación de nacionalidad
            // La nacionalidad no puede estar vacía ni contener el texto por defecto
            if (nacion.isEmpty() || nacion.equalsIgnoreCase("Nacionalidad")) {
                throw new Excepciones("Ingrese una nacionalidad valida.");
            }

            // Validación del instrumento
            // El instrumento no puede estar vacío ni contener el texto por defecto
            if (instrumento.isEmpty() || instrumento.equalsIgnoreCase("Instrumento")) {
                throw new Excepciones("Ingrese un instrumento valido.");
            }

            // Obtención de la fecha actual
            LocalDate fechaActual = LocalDate.now();

            // Cálculo de edad
            int edad = fechaActual.getYear() - fechaNacimiento.getYear();

            // Ajuste si todavía no cumplió años este año
            if (fechaActual.getMonthValue() < fechaNacimiento.getMonthValue()
                    || (fechaActual.getMonthValue() == fechaNacimiento.getMonthValue()
                    && fechaActual.getDayOfMonth() < fechaNacimiento.getDayOfMonth())) {

                edad--;
            }

            // Validación de edad mínima
            if (edad < 16) {

                throw new Excepciones("El músico debe tener al menos 16 años.");
            }

            // Creación del objeto Musico
            Musico musico = new Musico(
                    codBanda,
                    nombre,
                    fecha,
                    residencia,
                    nacion,
                    instrumento
            );

            // Actualización en base de datos
            Sql_Musico.update(musico, codigoAct);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "Músico actualizado correctamente");

        } catch (NumberFormatException e) {

            // Error cuando los códigos no son numéricos
            JOptionPane.showMessageDialog(null, ConstantesMensajes.codigoInvalido);

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_actualizarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musico_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musico_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musico_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musico_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musico_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBTN;
    private javax.swing.JLabel codBandaLBL;
    private javax.swing.JTextField codBandaTXT;
    private javax.swing.JTextField codigoActTXT;
    private javax.swing.JLabel codigoLBL;
    private javax.swing.JLabel fechaLBL;
    private javax.swing.JTextField fechaTXT;
    private javax.swing.JLabel instrumentoLBL;
    private javax.swing.JTextField intrumentoTXT;
    private javax.swing.JLabel nacionLBL;
    private javax.swing.JTextField nacionTXT;
    private javax.swing.JLabel nombreLBL;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JLabel residenciaLBL;
    private javax.swing.JTextField residenciaTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
