/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Album;

import services.Sql.Album.Sql_Album;
import configuracion.ConstantesMensajes;
import excepciones.Excepciones;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class Album_Borrar extends javax.swing.JFrame {

    /**
     * Creates new form Album_Borrar
     */
    public Album_Borrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoLBL = new javax.swing.JLabel();
        borrarBTN = new javax.swing.JButton();
        codigoTXT = new javax.swing.JTextField();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoLBL.setText("Introduce el codigo del Album");

        borrarBTN.setText("Borrar");
        borrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarBTNActionPerformed(evt);
            }
        });

        codigoTXT.setText("-1");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(textoLBL)
                .addGap(59, 59, 59)
                .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(64, 64, 64)
                .addComponent(borrarBTN)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLBL)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN)
                    .addComponent(borrarBTN))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarBTNActionPerformed
        try {

            // Se obtiene el código introducido en el campo de texto y se convierte a entero
            int codigo = Integer.parseInt(codigoTXT.getText().trim());

            // Validación: el código no puede ser negativo
            if (codigo < 0) {
                throw new Excepciones(ConstantesMensajes.codigoNegativo);
            }

            // Validación: comprobar si el álbum existe antes de eliminarlo
            if (!utils.Util_Clases.existeAlbumCodigo(codigo)) {
                throw new Excepciones("No existe un album con ese codigo.");
            }

            // Llamada al método que elimina el álbum en la base de datos
            Sql_Album.delete(codigo);

            // Mensaje de confirmación
            JOptionPane.showMessageDialog(null, "Album eliminado correctamente.");

        } catch (NumberFormatException e) {

            // Error cuando el valor introducido no es numérico
            JOptionPane.showMessageDialog(null, ConstantesMensajes.codigoInvalido);

        } catch (Excepciones e) {

            // Error controlado por reglas del sistema
            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error al intentar eliminar: " + e.getMessage());
        }
    }//GEN-LAST:event_borrarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Album_Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Album_Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Album_Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Album_Borrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Album_Borrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarBTN;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
