/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Album;

import services.Sql.Album.Sql_Album;
import configuracion.ConstantesMensajes;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isard
 */
public class Album_MostrarCodigo extends javax.swing.JFrame {

    /**
     * Creates new form Album_MostrarCodigo
     */
    public Album_MostrarCodigo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarBTN = new javax.swing.JButton();
        textoLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        albumTBL = new javax.swing.JTable();
        codigoTXT = new javax.swing.JTextField();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buscarBTN.setText("Buscar");
        buscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTNActionPerformed(evt);
            }
        });

        textoLBL.setText("Introduce el codigo del álbum");

        albumTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Autor", "Codigo_banda", "Codigo del musico", "Titulo", "Año de publicacion", "Tipo", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(albumTBL);

        codigoTXT.setText("-1");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(textoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(volverBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarBTN)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLBL)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBTN)
                    .addComponent(volverBTN))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTNActionPerformed

        try {

            // Se crea el modelo de la tabla con sus columnas
            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Codigo", "Autor", "Codigo_banda", "Codigo del Musico",
                        "Titulo", "Anio de publicacion", "Tipo", "Duracion"
                    }
            );

            // Se obtiene el código introducido por el usuario
            String textoCodigo = codigoTXT.getText().trim();

            // Validación: no puede estar vacío
            if (textoCodigo.isEmpty()) {
                throw new Excepciones("Ingrese un codigo.");
            }

            // Conversión a entero
            int codigo = Integer.parseInt(textoCodigo);

            // Validación: no puede ser negativo
            if (codigo < 0) {
                throw new Excepciones(ConstantesMensajes.codigoNegativo);
            }

            // Validación:  comprobar existencia real en BD
            if (!utils.Util_Clases.existeAlbumCodigo(codigo)) {
                throw new Excepciones("No existe un album con ese codigo.");
            }

            // Consulta a la base de datos
            String[][] matrizMostrar = Sql_Album.consultarPorCodigo(codigo);

            // Se asigna el modelo a la tabla
            albumTBL.setModel(modelo);

            boolean existeDatoReal = false;

            // Recorre la matriz obtenida de la BD
            for (int i = 0; i < matrizMostrar.length; i++) {

                // Validación de fila válida
                if (matrizMostrar[i] == null || matrizMostrar[i].length < 8) {
                    continue;
                }

                existeDatoReal = true;

                // Añade la fila a la tabla
                modelo.addRow(new Object[]{
                    matrizMostrar[i][0],
                    matrizMostrar[i][1],
                    matrizMostrar[i][2],
                    matrizMostrar[i][3],
                    matrizMostrar[i][4],
                    matrizMostrar[i][5],
                    matrizMostrar[i][6],
                    matrizMostrar[i][7]
                });
            }

            // Seguridad extra (por si la consulta viene vacía)
            if (!existeDatoReal) {
                throw new Excepciones("No existe un album con ese codigo.");
            }

        } catch (NumberFormatException e) {

            // Error si el código no es numérico
            JOptionPane.showMessageDialog(
                    null,
                    "El codigo debe ser numerico."
            );

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );

        } catch (Exception e) {

            JOptionPane.showMessageDialog(
                    null,
                    "Error inesperado: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_buscarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Album_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Album_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Album_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Album_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Album_MostrarCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable albumTBL;
    private javax.swing.JButton buscarBTN;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
