/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Cancion;


import services.Sql.Cancion.Sql_Cancion;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isard
 */
public class Cancion_MostrarCodigo extends javax.swing.JFrame {

    /**
     * Creates new form Cancion_MostrarCodigo
     */
    public Cancion_MostrarCodigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarBTN = new javax.swing.JButton();
        textoLBL = new javax.swing.JLabel();
        codigoTXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        albumCodigoTBL = new javax.swing.JTable();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buscarBTN.setText("Buscar");
        buscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTNActionPerformed(evt);
            }
        });

        textoLBL.setText("Introduce el codigo de la canción");

        codigoTXT.setText("-1");
        codigoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTXTActionPerformed(evt);
            }
        });

        albumCodigoTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Codigo_Album", "Posicion", "Titulo", "Compositor", "Duracion"
            }
        ));
        jScrollPane1.setViewportView(albumCodigoTBL);

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(textoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(volverBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscarBTN)
                .addGap(171, 171, 171))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoLBL)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBTN)
                    .addComponent(volverBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTXTActionPerformed

    private void buscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTNActionPerformed
        try {

            // Se crea el modelo de la tabla con sus columnas
            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Codigo", "Codigo_Album", "Posicion",
                        "Titulo", "Compositor", "Duracion"
                    }
            );

            // Se obtiene el código introducido por el usuario
            String textoCodigo = codigoTXT.getText().trim();

            // Validación: el campo no puede estar vacío
            if (textoCodigo.isEmpty()) {
                throw new Excepciones("Ingrese un código.");
            }

            // Conversión del código a entero
            int codigo = Integer.parseInt(textoCodigo);

            // Validación: el código no puede ser negativo
            if (codigo < 0) {
                throw new Excepciones("El código no puede ser negativo");
            }

            // Validación: comprobar si la banda existe
            if (!Sql_Cancion.existeCancion(codigo)) {
                System.out.println("Error: no existe la cancion con ese código");

            }

            // Se asigna el modelo a la tabla
            albumCodigoTBL.setModel(modelo);

            // Consulta a la base de datos por código
            String[][] matrizMostrar = Sql_Cancion.consultarPorCodigo(codigo);

            boolean existeDatoReal = false;

            // Recorre los resultados obtenidos
            for (int i = 0; i < matrizMostrar.length; i++) {

                if (matrizMostrar[i] == null || matrizMostrar[i].length < 6) {
                    continue;
                }

                existeDatoReal = true;

                modelo.addRow(new Object[]{
                    matrizMostrar[i][0],
                    matrizMostrar[i][1],
                    matrizMostrar[i][2],
                    matrizMostrar[i][3],
                    matrizMostrar[i][4],
                    matrizMostrar[i][5]
                });
            }

            // Si no hay datos válidos en la matriz
            if (!existeDatoReal) {
                throw new Excepciones("No existen canciones válidas con ese código.");
            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Debes introducir un número válido");

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }

    }//GEN-LAST:event_buscarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancion_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancion_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancion_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancion_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancion_MostrarCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable albumCodigoTBL;
    private javax.swing.JButton buscarBTN;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
