/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import services.ficheros.importar.Importar_Album;
import services.ficheros.importar.Importar_Cancion;
import services.ficheros.importar.Importar_banda;
import services.ficheros.Importador;
import services.ficheros.importar.Importar_Musico;
import excepciones.Excepciones;
import java.io.File;

/**
 *
 * @author isard
 */
public class OpcionImportar extends javax.swing.JFrame {

    /**
     * Creates new form OpcionImportar
     */
    public OpcionImportar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        volverBTN1 = new javax.swing.JButton();
        importarBTN = new javax.swing.JButton();
        tablaCMB = new javax.swing.JComboBox<>();
        formatoCMB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Elige una opcion de tabla y formato para importar");

        volverBTN1.setText("Volver");
        volverBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTN1ActionPerformed(evt);
            }
        });

        importarBTN.setText("Importar");
        importarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarBTNActionPerformed(evt);
            }
        });

        tablaCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda", "Musico", "Album", "Cancion" }));

        formatoCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Json", "TXT", "Binario", "CSV" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(opcionLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tablaCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formatoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volverBTN1)
                                .addGap(73, 73, 73)
                                .addComponent(importarBTN)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(opcionLBL)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablaCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN1)
                    .addComponent(importarBTN))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTN1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTN1ActionPerformed

    private void importarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarBTNActionPerformed

        // Se obtiene la tabla seleccionada del JComboBox.
        String tabla = tablaCMB.getSelectedItem().toString().trim();

// Se obtiene el formato seleccionado del JComboBox.
        String formato = formatoCMB.getSelectedItem().toString().trim();

// Se formatea el nombre de la tabla:
// Primera letra en mayúscula y el resto en minúscula.
        tabla = Character.toUpperCase(tabla.charAt(0))
                + tabla.substring(1).toLowerCase();

// Se convierte el formato a mayúsculas.
        formato = formato.toUpperCase();

// Se crea la opción combinando tabla y formato.
        String opcion = tabla + "_" + formato;

// Variables para almacenar la ruta y el archivo.
        String ruta;
        File archivo;

        try {

            // Matriz donde se almacenarán los datos importados.
            String[][] datos = null;

            // Estructura switch para determinar qué archivo importar.
            switch (opcion) {

                // =========================
                // BANDA → MYSQL
                // =========================
                case "Banda_TXT" -> {

                    // Ruta del archivo TXT.
                    ruta = "TXT\\banda.txt";

                    // Creación del objeto File.
                    archivo = new File(ruta);

                    // Importación de datos desde TXT.
                    datos = Importar_banda.importarTexto(archivo);

                    // Inserción de datos en MySQL.
                    Importador.importar_MySQL("Banda", datos);
                }

                case "Banda_CSV" -> {

                    ruta = "CSV\\banda.csv";
                    archivo = new File(ruta);

                    // Importación desde archivo CSV.
                    datos = Importar_banda.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Banda", datos);
                }

                case "Banda_JSON" -> {

                    ruta = "JSON\\banda.json";
                    archivo = new File(ruta);

                    // Importación desde archivo JSON.
                    datos = Importar_banda.importarJSON(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Banda", datos);
                }

                case "Banda_BINARIO" -> {

                    ruta = "Binario\\banda.bin";
                    archivo = new File(ruta);

                    // Importación desde archivo binario.
                    datos = Importar_banda.importarBinario(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Banda", datos);
                }

                // =========================
                // MUSICO → MYSQL
                // =========================
                case "Musico_TXT" -> {

                    ruta = "TXT\\Musico.txt";
                    archivo = new File(ruta);

                    // Importación desde TXT.
                    datos = Importar_Musico.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Musico", datos);
                }

                case "Musico_CSV" -> {

                    ruta = "CSV\\Musico.csv";
                    archivo = new File(ruta);

                    // Importación desde CSV.
                    datos = Importar_Musico.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Musico", datos);
                }

                case "Musico_JSON" -> {

                    ruta = "JSON\\Musico.json";
                    archivo = new File(ruta);

                    // Importación desde JSON.
                    datos = Importar_Musico.importarJSON(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Musico", datos);
                }

                case "Musico_BINARIO" -> {

                    ruta = "Binario\\Musico.bin";
                    archivo = new File(ruta);

                    // Importación desde archivo binario.
                    datos = Importar_Musico.importarBinario(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Musico", datos);
                }

                // =========================
                // ALBUM → MYSQL
                // =========================
                case "Album_TXT" -> {

                    ruta = "TXT\\Album.txt";
                    archivo = new File(ruta);

                    // Importación desde TXT.
                    datos = Importar_Album.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Album", datos);
                }

                case "Album_CSV" -> {

                    ruta = "CSV\\Album.csv";
                    archivo = new File(ruta);

                    // Importación desde CSV.
                    datos = Importar_Album.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Album", datos);
                }

                case "Album_JSON" -> {

                    ruta = "JSON\\Album.json";
                    archivo = new File(ruta);

                    // Importación desde JSON.
                    datos = Importar_Album.importarJSON(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Album", datos);
                }

                case "Album_BINARIO" -> {

                    ruta = "Binario\\Album.bin";
                    archivo = new File(ruta);

                    // Importación desde archivo binario.
                    datos = Importar_Album.importarBinario(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Album", datos);
                }

                // =========================
                // CANCION → MYSQL
                // =========================
                case "Cancion_TXT" -> {

                    ruta = "TXT\\Cancion.txt";
                    archivo = new File(ruta);

                    // Importación desde TXT.
                    datos = Importar_Cancion.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Cancion", datos);
                }

                case "Cancion_CSV" -> {

                    ruta = "CSV\\Cancion.csv";
                    archivo = new File(ruta);

                    // Importación desde CSV.
                    datos = Importar_Cancion.importarTexto(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Cancion", datos);
                }

                case "Cancion_JSON" -> {

                    ruta = "JSON\\Cancion.json";
                    archivo = new File(ruta);

                    // Importación desde JSON.
                    datos = Importar_Cancion.importarJSON(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Cancion", datos);
                }

                case "Cancion_BINARIO" -> {

                    ruta = "Binario\\Cancion.bin";
                    archivo = new File(ruta);

                    // Importación desde archivo binario.
                    datos = Importar_Cancion.importarBinario(archivo);

                    // Inserción en MySQL.
                    Importador.importar_MySQL("Cancion", datos);
                }

                // Opción inválida.
                default -> {

                    throw new Excepciones("Opcion no valida.");
                }
            }

        } catch (Excepciones e) {

            // Mostrar errores personalizados.
            System.out.println(e.getMessage());

        } catch (Exception e) {

            // Captura de errores inesperados.
            System.out.println("Error : " + e.getMessage());

            // Mostrar trazado del error.
            e.printStackTrace();
        }


    }//GEN-LAST:event_importarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionImportar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> formatoCMB;
    private javax.swing.JButton importarBTN;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JComboBox<String> tablaCMB;
    private javax.swing.JButton volverBTN1;
    // End of variables declaration//GEN-END:variables
}
