/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import services.ficheros.importar.Importar_Album;
import services.ficheros.importar.Importar_Cancion;
import services.ficheros.importar.Importar_banda;
import services.ficheros.Importador;
import services.ficheros.importar.Importar_Musico;
import excepciones.Excepciones;
import java.io.File;

/**
 *
 * @author isard
 */
public class OpcionImportar extends javax.swing.JFrame {

    /**
     * Creates new form OpcionImportar
     */
    public OpcionImportar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionLBL = new javax.swing.JLabel();
        volverBTN1 = new javax.swing.JButton();
        importarBTN = new javax.swing.JButton();
        tablaCMB = new javax.swing.JComboBox<>();
        formatoCMB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcionLBL.setText("Elige una opcion de tabla y formato para importar");

        volverBTN1.setText("Volver");
        volverBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTN1ActionPerformed(evt);
            }
        });

        importarBTN.setText("Importar");
        importarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarBTNActionPerformed(evt);
            }
        });

        tablaCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda", "Musico", "Album", "Cancion" }));

        formatoCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Json", "TXT", "Binario", "CSV" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(opcionLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tablaCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formatoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volverBTN1)
                                .addGap(73, 73, 73)
                                .addComponent(importarBTN)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(opcionLBL)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablaCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatoCMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN1)
                    .addComponent(importarBTN))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTN1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTN1ActionPerformed

    private void importarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarBTNActionPerformed

   

        // Tabla seleccionada
        String tabla = tablaCMB.getSelectedItem().toString().trim();

        // Formato seleccionado
        String formato = formatoCMB.getSelectedItem().toString().trim();

        // Normalización de nombres
        tabla = Character.toUpperCase(tabla.charAt(0))
                + tabla.substring(1).toLowerCase();

        formato = formato.toUpperCase();

        String opcion = tabla + "_" + formato;

        File archivo;
        String[][] datos;

        try {

            switch (opcion) {

                // =========================
                // BANDA
                // =========================
                case "Banda_TXT" -> {
                    archivo = new File("Ficheros\\TXT\\banda.txt");
                    datos = Importar_banda.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Banda TXT)");
                    }

                    Importador.importar_MySQL("Banda", datos);
                }

                case "Banda_CSV" -> {
                    archivo = new File("Ficheros\\CSV\\banda.csv");
                    datos = Importar_banda.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Banda CSV)");
                    }

                    Importador.importar_MySQL("Banda", datos);
                }

                case "Banda_JSON" -> {
                    archivo = new File("Ficheros\\JSON\\banda.json");
                    datos = Importar_banda.importarJSON(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Banda JSON)");
                    }

                    Importador.importar_MySQL("Banda", datos);
                }

                case "Banda_BINARIO" -> {
                    archivo = new File("Ficheros\\Binario\\banda.bin");
                    datos = Importar_banda.importarBinario(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Banda BINARIO)");
                    }

                    Importador.importar_MySQL("Banda", datos);
                }

                // =========================
                // MUSICO
                // =========================
                case "Musico_TXT" -> {
                    archivo = new File("Ficheros\\TXT\\Musico.txt");
                    datos = Importar_Musico.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Musico TXT)");
                    }

                    Importador.importar_MySQL("Musico", datos);
                }

                case "Musico_CSV" -> {
                    archivo = new File("Ficheros\\CSV\\Musico.csv");
                    datos = Importar_Musico.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Musico CSV)");
                    }

                    Importador.importar_MySQL("Musico", datos);
                }

                case "Musico_JSON" -> {
                    archivo = new File("Ficheros\\JSON\\Musico.json");
                    datos = Importar_Musico.importarJSON(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Musico JSON)");
                    }

                    Importador.importar_MySQL("Musico", datos);
                }

                case "Musico_BINARIO" -> {
                    archivo = new File("Ficheros\\Binario\\Musico.bin");
                    datos = Importar_Musico.importarBinario(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Musico BINARIO)");
                    }

                    Importador.importar_MySQL("Musico", datos);
                }

                // =========================
                // ALBUM
                // =========================
                case "Album_TXT" -> {
                    archivo = new File("Ficheros\\TXT\\Album.txt");
                    datos = Importar_Album.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Album TXT)");
                    }

                    Importador.importar_MySQL("Album", datos);
                }

                case "Album_CSV" -> {
                    archivo = new File("Ficheros\\CSV\\Album.csv");
                    datos = Importar_Album.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Album CSV)");
                    }

                    Importador.importar_MySQL("Album", datos);
                }

                case "Album_JSON" -> {
                    archivo = new File("JSON\\Album.json");
                    datos = Importar_Album.importarJSON(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Album JSON)");
                    }

                    Importador.importar_MySQL("Album", datos);
                }

                case "Album_BINARIO" -> {
                    archivo = new File("Ficheros\\Binario\\Album.bin");
                    datos = Importar_Album.importarBinario(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Album BINARIO)");
                    }

                    Importador.importar_MySQL("Album", datos);
                }

                // =========================
                // CANCION
                // =========================
                case "Cancion_TXT" -> {
                    archivo = new File("Ficheros\\TXT\\Cancion.txt");
                    datos = Importar_Cancion.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Cancion TXT)");
                    }

                    Importador.importar_MySQL("Cancion", datos);
                }

                case "Cancion_CSV" -> {
                    archivo = new File("Ficheros\\CSV\\Cancion.csv");
                    datos = Importar_Cancion.importarTexto(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Cancion CSV)");
                    }

                    Importador.importar_MySQL("Cancion", datos);
                }

                case "Cancion_JSON" -> {
                    archivo = new File("Ficheros\\JSON\\Cancion.json");
                    datos = Importar_Cancion.importarJSON(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Cancion JSON)");
                    }

                    Importador.importar_MySQL("Cancion", datos);
                }

                case "Cancion_BINARIO" -> {
                    archivo = new File("Ficheros\\Binario\\Cancion.bin");
                    datos = Importar_Cancion.importarBinario(archivo);

                    if (!utils.Util_Clases.datosValidos(datos)) {
                        throw new Excepciones("Archivo vacío (Cancion BINARIO)");
                    }

                    Importador.importar_MySQL("Cancion", datos);
                }

                default ->
                    throw new Excepciones("Opcion no valida");
            }

        } catch (Excepciones e) {
            System.out.println(e.getMessage());

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_importarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionImportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionImportar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> formatoCMB;
    private javax.swing.JButton importarBTN;
    private javax.swing.JLabel opcionLBL;
    private javax.swing.JComboBox<String> tablaCMB;
    private javax.swing.JButton volverBTN1;
    // End of variables declaration//GEN-END:variables
}
