/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Banda;

import modelo.Banda;
import services.Contenedor_tablas.Contenedor_Banda;
import services.Sql.Banda.Sql_banda;
import excepciones.Excepciones;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class Banda_Insertar extends javax.swing.JFrame {

    /**
     * Creates new form Swing_Banda
     */
    public Banda_Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertarBTN = new javax.swing.JButton();
        nombreLBL = new javax.swing.JLabel();
        anosLBL = new javax.swing.JLabel();
        origenLBL = new javax.swing.JLabel();
        generoLBL = new javax.swing.JLabel();
        nombreTXT = new javax.swing.JTextField();
        actuacionTXT = new javax.swing.JTextField();
        origenTXT = new javax.swing.JTextField();
        generoTXT = new javax.swing.JTextField();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        insertarBTN.setText("Insertar");
        insertarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBTNActionPerformed(evt);
            }
        });

        nombreLBL.setText("Nombre");

        anosLBL.setText("Años de actuacion");

        origenLBL.setText("Lugar de origen");

        generoLBL.setText("Genero");

        nombreTXT.setText("nombre");
        nombreTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTXTActionPerformed(evt);
            }
        });

        actuacionTXT.setText("1960-actualidad");

        origenTXT.setText("origen");

        generoTXT.setText("genero");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generoLBL)
                    .addComponent(origenLBL)
                    .addComponent(anosLBL)
                    .addComponent(nombreLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origenTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actuacionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(71, 71, 71)
                .addComponent(insertarBTN)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLBL)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(origenTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(origenLBL))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generoLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anosLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(actuacionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarBTN)
                    .addComponent(volverBTN))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTXTActionPerformed

    private void insertarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBTNActionPerformed
        try {

            // Obtención de datos del formulario
            String nombre = nombreTXT.getText().trim();
            String origen = origenTXT.getText().trim();
            String genero = generoTXT.getText().trim();
            String actuacion = actuacionTXT.getText().trim();

            // Validación del nombre
            // El nombre no puede estar vacío ni contener el texto por defecto
            if (nombre.isEmpty() || nombre.equalsIgnoreCase("Nombre")) {
                throw new Excepciones("Ingrese un nombre valido.");
            }

            // Comprobación de existencia de la banda en la base de datos
            if (Sql_banda.existeBanda(nombre)) {
                throw new Excepciones("Ya existe una banda con ese nombre");
            }

            // Validación del origen
            // El origen no puede estar vacío ni contener el texto por defecto
            if (origen.isEmpty() || origen.equalsIgnoreCase("Origen")) {
                throw new Excepciones("Ingrese un origen valido.");
            }

            // Validación del género
            // El género no puede estar vacío ni contener el texto por defecto
            if (genero.isEmpty() || genero.equalsIgnoreCase("Genero")) {
                throw new Excepciones("Ingrese un genero valido.");
            }

            // Validación de la actuación
            // La actuación no puede estar vacía ni contener el texto por defecto
            if (actuacion.isEmpty() || actuacion.equalsIgnoreCase("Actuacion")) {
                throw new Excepciones("Ingrese una actuacion valida.");
            }

            // Ejemplo: "1980-actualidad" o "1980-2020"
            String[] partes = actuacion.split("-");

            if (partes.length != 2) {
                throw new Excepciones("Formato de actuación inválido. Use: 1960-actualidad");
            }

            int anioInicio;
            int anioFin;

            // Validación del año inicio
            try {
                anioInicio = Integer.parseInt(partes[0].trim());
            } catch (Exception e) {
                throw new Excepciones("El año de inicio no es válido.");
            }

            // Validación del año fin
            if (partes[1].trim().equalsIgnoreCase("actualidad")) {
                anioFin = LocalDate.now().getYear();
            } else {
                try {
                    anioFin = Integer.parseInt(partes[1].trim());
                } catch (Exception e) {
                    throw new Excepciones("El año final no es válido.");
                }
            }

            // Validación lógica
            if (anioFin < anioInicio) {
                throw new Excepciones("El año final no puede ser menor que el año inicial.");
            }

            // Cálculo de años de actividad
            int aniosActuacion = anioFin - anioInicio;

             // VAlidación maxima
            if (aniosActuacion > 80) {
                throw new Excepciones("La banda no puede superar los 80 años de actuación.");
            }

            // Creación del objeto Banda
            Banda banda = new Banda(
                    nombre,
                    actuacion,
                    origen,
                    genero
            );

            // Inserción en base de datos
            Sql_banda.insertar(banda);

            // Guardado en fichero TXT
            Contenedor_Banda.guardarBandaTXT(banda);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "Banda insertada correctamente");

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_insertarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banda_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banda_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banda_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banda_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banda_Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actuacionTXT;
    private javax.swing.JLabel anosLBL;
    private javax.swing.JLabel generoLBL;
    private javax.swing.JTextField generoTXT;
    private javax.swing.JButton insertarBTN;
    private javax.swing.JLabel nombreLBL;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JLabel origenLBL;
    private javax.swing.JTextField origenTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
