/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Album;

import modelo.Album;
import services.Sql.Album.Sql_Album;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import utils.Util_Tiempo;

/**
 *
 * @author isard
 */
public class Album_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Album_Actualizar
     */
    public Album_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoLBL = new javax.swing.JLabel();
        actualizarBTN = new javax.swing.JButton();
        autorLBL = new javax.swing.JLabel();
        bandaLBL = new javax.swing.JLabel();
        musicoLBL = new javax.swing.JLabel();
        tituloLBL = new javax.swing.JLabel();
        publicacionLBL = new javax.swing.JLabel();
        tipoLBL = new javax.swing.JLabel();
        duracionLBL = new javax.swing.JLabel();
        codigoLBL = new javax.swing.JLabel();
        codigoBandaTXT = new javax.swing.JTextField();
        codigoMusicoTXT = new javax.swing.JTextField();
        tituloTXT = new javax.swing.JTextField();
        fechaTXT = new javax.swing.JTextField();
        duracionTXT = new javax.swing.JTextField();
        albumCodigoTXT = new javax.swing.JTextField();
        autorCB = new javax.swing.JComboBox<>();
        tipoCB = new javax.swing.JComboBox<>();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoLBL.setText("introduce los nuevos datos");

        actualizarBTN.setText("Actualizar");
        actualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBTNActionPerformed(evt);
            }
        });

        autorLBL.setText("Autor");

        bandaLBL.setText("Codigo de la banda");

        musicoLBL.setText("Codigo del musico");

        tituloLBL.setText("Titulo");

        publicacionLBL.setText("Año de publicacion");

        tipoLBL.setText("Tipo");

        duracionLBL.setText("Duracion");

        codigoLBL.setText("Introduce el codigo del album");

        codigoBandaTXT.setText("-1");

        codigoMusicoTXT.setText("-1");

        tituloTXT.setText("Titulo");

        fechaTXT.setText("YYYY");

        duracionTXT.setText("HH:MM:SS");

        albumCodigoTXT.setText("-1");

        autorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda", "Musico" }));

        tipoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudio", "Directo", "Recopilatorio" }));

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(textoLBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(codigoLBL)
                    .addComponent(bandaLBL)
                    .addComponent(autorLBL)
                    .addComponent(musicoLBL)
                    .addComponent(tituloLBL)
                    .addComponent(publicacionLBL)
                    .addComponent(tipoLBL)
                    .addComponent(duracionLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(codigoBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codigoMusicoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(albumCodigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(autorCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(29, 29, 29)
                .addComponent(actualizarBTN)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoLBL)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autorLBL)
                    .addComponent(autorCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bandaLBL)
                    .addComponent(codigoBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicoLBL)
                    .addComponent(codigoMusicoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLBL)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicacionLBL)
                    .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLBL)
                    .addComponent(tipoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracionLBL)
                    .addComponent(duracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLBL)
                    .addComponent(albumCodigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarBTN)
                    .addComponent(volverBTN))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBTNActionPerformed
        try {

            // Validación: autor
            // Comprueba que el usuario haya seleccionado un autor en el ComboBox
            if (autorCB.getSelectedItem() == null) {
                throw new Excepciones("Debe  seleccionar un autor.");
            }

            // Se obtiene el autor y se eliminan espacios en blanco
            String autor = autorCB.getSelectedItem().toString().trim();

            // Obtención de datos del formulario
            String titulo = tituloTXT.getText().trim();
            String fecha = fechaTXT.getText().trim();
            String duracion = duracionTXT.getText().trim();
            String albumCodigoStr = albumCodigoTXT.getText().trim();

            // Validación del título
            if (titulo.isEmpty() || titulo.equals("Titulo")) {
                throw new Excepciones("Ingrese un titulo valido.");
            }

            // Validación del año
            if (fecha.isEmpty() || fecha.equals("YYYY")) {
                throw new Excepciones("Ingrese un anio valido.");
            }

            if (!fecha.matches("\\d{4}")) {
                throw new Excepciones("El anio debe tener 4 numeros.");
            }

            // Validación del tipo
            if (tipoCB.getSelectedItem() == null) {
                throw new Excepciones("Seleccione un tipo.");
            }

            // Validación de la duración
            // La duración no puede estar vacía ni contener el texto por defecto
            if (duracion.isEmpty() || duracion.equals("HH:MM:SS")) {
                throw new Excepciones("Ingrese una duracion valida.");
            }

            // La duración debe tener formato HH:MM:SS
            if (!duracion.matches("\\d{2}:\\d{2}:\\d{2}")) {
                throw new Excepciones(
                        "La duracion debe tener formato HH:MM:SS."
                );
            }

            // Separación de partes
            String[] partesDuracion = duracion.split(":");

            int horas = Integer.parseInt(partesDuracion[0]);
            int minutos = Integer.parseInt(partesDuracion[1]);
            int segundos = Integer.parseInt(partesDuracion[2]);

            // Normalización del tiempo
            duracion = Util_Tiempo.normalizarDuracion(duracion);

            // El tiempo no puede ser 00:00:00
            if (horas == 0 && minutos == 0 && segundos == 0) {
                throw new Excepciones(
                        "La duración no puede ser 00:00:00."
                );
            }

            // Validación del código del álbum
            if (albumCodigoStr.isEmpty()) {
                throw new Excepciones("Ingrese el codigo del album.");
            }

            if (!albumCodigoStr.matches("\\d+")) {
                throw new Excepciones("El codigo del album debe ser numerico.");
            }

            int albumCodigo = Integer.parseInt(albumCodigoStr);

            // Comprobación en base de datos
            if (!utils.Util_Clases.existeAlbumCodigo(albumCodigo)) {
                throw new Excepciones("No existe un álbum con ese código.");
            }

            // Normalización de duración
            duracion = Util_Tiempo.normalizarDuracion(duracion);

            // Variables de relación
            Integer codigoBanda = null;
            Integer codigoMusico = null;

            // Autor: Músico 
            if (autor.equalsIgnoreCase("Musico")) {

                String musicoStr = codigoMusicoTXT.getText().trim();

                if (musicoStr.isEmpty()) {
                    throw new Excepciones("Ingrese el codigo del musico.");
                }

                if (!musicoStr.matches("\\d+")) {
                    throw new Excepciones("El codigo del musico debe ser numerico.");
                }

                codigoMusico = Integer.parseInt(musicoStr);

                // Comprobación de existencia del músico en la base de datos
                if (!utils.Util_Clases.existeMusicoPorCodigo(codigoMusico)) {
                    JOptionPane.showMessageDialog(null, "No existe un músico con ese código.");
                    return;
                }
            } // Autor: Banda 
            else if (autor.equalsIgnoreCase("Banda")) {

                String bandaStr = codigoBandaTXT.getText().trim();

                if (bandaStr.isEmpty()) {
                    throw new Excepciones("Ingrese el codigo de la banda.");
                }

                if (!bandaStr.matches("\\d+")) {
                    throw new Excepciones("El codigo de la banda debe ser numerico.");
                }

                codigoBanda = Integer.parseInt(bandaStr);

                // Comprobación de existencia de la banda en la base de datos
                if (!utils.Util_Clases.existeBandaCodigo(codigoBanda)) {
                    JOptionPane.showMessageDialog(null, "No existe una banda con ese código.");
                    return;
                }
            }

            // Creación del objeto Album
            Album album = new Album(
                    autor,
                    codigoBanda,
                    codigoMusico,
                    titulo,
                    Integer.parseInt(fecha),
                    tipoCB.getSelectedItem().toString(),
                    duracion
            );

            // Actualización en base de datos
            Sql_Album.update(album, albumCodigo);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "Album actualizado correctamente.");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Los codigos y el anio deben ser numericos.");

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_actualizarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Album_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Album_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Album_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Album_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Album_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBTN;
    private javax.swing.JTextField albumCodigoTXT;
    private javax.swing.JComboBox<String> autorCB;
    private javax.swing.JLabel autorLBL;
    private javax.swing.JLabel bandaLBL;
    private javax.swing.JTextField codigoBandaTXT;
    private javax.swing.JLabel codigoLBL;
    private javax.swing.JTextField codigoMusicoTXT;
    private javax.swing.JLabel duracionLBL;
    private javax.swing.JTextField duracionTXT;
    private javax.swing.JTextField fechaTXT;
    private javax.swing.JLabel musicoLBL;
    private javax.swing.JLabel publicacionLBL;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JComboBox<String> tipoCB;
    private javax.swing.JLabel tipoLBL;
    private javax.swing.JLabel tituloLBL;
    private javax.swing.JTextField tituloTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
