/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Album;

import modelo.Album;
import services.Contenedor_tablas.Contenedor_Album;
import services.Sql.Album.Sql_Album;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import utils.Util_Tiempo;

/**
 *
 * @author isard
 */
public class Album_Insertar extends javax.swing.JFrame {

    /**
     * Creates new form Album_Insertar
     */
    public Album_Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoLBL = new javax.swing.JLabel();
        autorLBL = new javax.swing.JLabel();
        codBandaLBL = new javax.swing.JLabel();
        codMusicoLBL = new javax.swing.JLabel();
        tituloLBL = new javax.swing.JLabel();
        publicacionLBL = new javax.swing.JLabel();
        tipoLBL = new javax.swing.JLabel();
        DuracionLBL = new javax.swing.JLabel();
        insertarBTN = new javax.swing.JButton();
        codigoBandaTXT = new javax.swing.JTextField();
        codMusicoTXT = new javax.swing.JTextField();
        tituloTXT = new javax.swing.JTextField();
        fechaTXT = new javax.swing.JTextField();
        tiempoTXT = new javax.swing.JTextField();
        autorCB = new javax.swing.JComboBox<>();
        tipoCB = new javax.swing.JComboBox<>();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoLBL.setText("Introduce los datos");

        autorLBL.setText("Autor");

        codBandaLBL.setText("Codigo de la banda");

        codMusicoLBL.setText("Codigo del musico");

        tituloLBL.setText("Titulo");

        publicacionLBL.setText("Año de publicacion");

        tipoLBL.setText("Tipo");

        DuracionLBL.setText("Duracion");

        insertarBTN.setText("Insertar");
        insertarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBTNActionPerformed(evt);
            }
        });

        codigoBandaTXT.setText("NULL");
        codigoBandaTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBandaTXTActionPerformed(evt);
            }
        });

        codMusicoTXT.setText("Codigo del musico");

        tituloTXT.setText("Titulo");

        fechaTXT.setText("YYYY");

        tiempoTXT.setText("HH:MM:SS");

        autorCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banda", "Musico" }));

        tipoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudio", "Directo", "Recopilatorio" }));

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(textoLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codBandaLBL)
                            .addComponent(autorLBL)
                            .addComponent(codMusicoLBL)
                            .addComponent(tituloLBL)
                            .addComponent(publicacionLBL)
                            .addComponent(tipoLBL)
                            .addComponent(DuracionLBL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codMusicoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autorCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(volverBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertarBTN)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoLBL)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autorLBL)
                    .addComponent(autorCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codBandaLBL)
                    .addComponent(codigoBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codMusicoLBL)
                    .addComponent(codMusicoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLBL)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicacionLBL)
                    .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLBL)
                    .addComponent(tipoCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DuracionLBL)
                    .addComponent(tiempoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volverBTN)
                    .addComponent(insertarBTN))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoBandaTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBandaTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoBandaTXTActionPerformed

    private void insertarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBTNActionPerformed
        try {

            // Validación: autor obligatorio
            if (autorCB.getSelectedItem() == null) {
                throw new Excepciones("Debe seleccionar un autor.");
            }

            // Obtención de datos del formulario
            String titulo = tituloTXT.getText().trim();
            String fecha = fechaTXT.getText().trim();
            String duracion = tiempoTXT.getText().trim();
            String tipo = tipoCB.getSelectedItem().toString().trim();
            String autor = autorCB.getSelectedItem().toString().trim();

            // Validación del título
            if (tituloTXT.getText().equals("Titulo") || tituloTXT.getText().isEmpty()) {
                throw new Excepciones("Ingrese un titulo valido.");
            }

            if (Sql_Album.existeAlbumTitulo(tituloTXT.getText().trim())) {
                throw new Excepciones("Ya existe un album con ese nombre.");
            }

            // Año
            if (fechaTXT.getText().equals("YYYY") || fechaTXT.getText().isEmpty()) {
                throw new Excepciones("Ingrese un año valido.");
            }

            if (!fechaTXT.getText().matches("\\d{4}")) {
                throw new Excepciones("El año debe tener 4 numeros.");
            }

            // Tipo
            if (tipoCB.getSelectedItem() == null) {
                throw new Excepciones("Seleccione un tipo.");
            }

            // Validación de la duración
            // La duración no puede estar vacía ni contener el texto por defecto
            if (duracion.isEmpty() || duracion.equals("HH:MM:SS")) {
                throw new Excepciones("Ingrese una duracion valida.");
            }

            // La duración debe tener formato HH:MM:SS
            if (!duracion.matches("\\d{2}:\\d{2}:\\d{2}")) {
                throw new Excepciones(
                        "La duracion debe tener formato HH:MM:SS."
                );
            }

            // Separación de partes
            String[] partesDuracion = duracion.split(":");

            int horas = Integer.parseInt(partesDuracion[0]);
            int minutos = Integer.parseInt(partesDuracion[1]);
            int segundos = Integer.parseInt(partesDuracion[2]);

            // Normalización del tiempo
            duracion = Util_Tiempo.normalizarDuracion(duracion);

            // El tiempo no puede ser 00:00:00
            if (horas == 0 && minutos == 0 && segundos == 0) {
                throw new Excepciones(
                        "La duración no puede ser 00:00:00."
                );
            }

            // Variables
            Integer codigoBanda = null;
            Integer codigoMusico = null;

            // MÚSICO
            if (autor.equals("Musico")) {

                if (codMusicoTXT.getText().isEmpty()) {
                    throw new Excepciones("Ingrese el codigo del musico.");
                }

                if (!codMusicoTXT.getText().matches("\\d+")) {
                    throw new Excepciones("El código de músico debe ser numérico.");
                }
                codigoMusico = Integer.parseInt(codMusicoTXT.getText());

                if (!utils.Util_Clases.existeMusicoPorCodigo(codigoMusico)) {
                    JOptionPane.showMessageDialog(null, "El código de músico no existe.");
                    return;
                }
            } // BANDA
            else if (autor.equals("Banda")) {

                if (codigoBandaTXT.getText().isEmpty()) {
                    throw new Excepciones("Ingrese el codigo de la banda.");
                }

                if (!codigoBandaTXT.getText().matches("\\d+")) {
                    throw new Excepciones("El código de banda debe ser numérico.");
                }

                codigoBanda = Integer.parseInt(codigoBandaTXT.getText());

                if (!utils.Util_Clases.existeBandaCodigo(codigoBanda)) {
                    JOptionPane.showMessageDialog(null, "El código de banda no existe.");
                    return;
                }
            }

            // Crear álbum
            Album album = new Album(
                    autor,
                    codigoBanda,
                    codigoMusico,
                    tituloTXT.getText(),
                    Integer.parseInt(fechaTXT.getText()),
                    tipoCB.getSelectedItem().toString(),
                    duracion
            );

            // Insertar
            Sql_Album.insertar(album);
            Contenedor_Album.guardarAlbumTXT(album);

            JOptionPane.showMessageDialog(null, "Album insertado correctamente.");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Los codigos y el anio deben ser numericos.");

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_insertarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Album_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Album_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Album_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Album_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Album_Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DuracionLBL;
    private javax.swing.JComboBox<String> autorCB;
    private javax.swing.JLabel autorLBL;
    private javax.swing.JLabel codBandaLBL;
    private javax.swing.JLabel codMusicoLBL;
    private javax.swing.JTextField codMusicoTXT;
    private javax.swing.JTextField codigoBandaTXT;
    private javax.swing.JTextField fechaTXT;
    private javax.swing.JButton insertarBTN;
    private javax.swing.JLabel publicacionLBL;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JTextField tiempoTXT;
    private javax.swing.JComboBox<String> tipoCB;
    private javax.swing.JLabel tipoLBL;
    private javax.swing.JLabel tituloLBL;
    private javax.swing.JTextField tituloTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
