/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Musico;

import modelo.Musico;
import services.Contenedor_tablas.Contenedor_Musico;
import services.Sql.Musico.Sql_Musico;
import configuracion.ConstantesMensajes;
import excepciones.Excepciones;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class Musico_Insertar extends javax.swing.JFrame {

    /**
     * Creates new form Musico_Insertar
     */
    public Musico_Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLBL = new javax.swing.JLabel();
        nombreLBL = new javax.swing.JLabel();
        fechaLBL = new javax.swing.JLabel();
        residenciaLBL = new javax.swing.JLabel();
        nacionalidadLBL = new javax.swing.JLabel();
        instrumentoLBL = new javax.swing.JLabel();
        CodBandaTXT = new javax.swing.JTextField();
        nombreTXT = new javax.swing.JTextField();
        fechaTXT = new javax.swing.JTextField();
        residenciaTXT = new javax.swing.JTextField();
        nacionalidadTXT = new javax.swing.JTextField();
        instrumentoTXT = new javax.swing.JTextField();
        insertarBTN = new javax.swing.JButton();
        volverBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoLBL.setText("Codigo de la banda");

        nombreLBL.setText("Nombre");

        fechaLBL.setText("Fecha de nacimiento");

        residenciaLBL.setText("Residencia");

        nacionalidadLBL.setText("Nacionalidad");

        instrumentoLBL.setText("Instrumento");

        CodBandaTXT.setText("-1");

        nombreTXT.setText("Nombre");

        fechaTXT.setText("YYYY/MM/DD");

        residenciaTXT.setText("Residencia");

        nacionalidadTXT.setText("Nacionalidad");

        instrumentoTXT.setText("Instrumento");

        insertarBTN.setText("Insertar");
        insertarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBTNActionPerformed(evt);
            }
        });

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduce los datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(instrumentoLBL)
                        .addComponent(nacionalidadLBL)
                        .addComponent(residenciaLBL)
                        .addComponent(fechaLBL)
                        .addComponent(nombreLBL)
                        .addComponent(codigoLBL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(volverBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CodBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(residenciaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacionalidadTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(insertarBTN))
                        .addComponent(instrumentoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLBL)
                    .addComponent(CodBandaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLBL)
                    .addComponent(nombreTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaLBL)
                    .addComponent(fechaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(residenciaLBL)
                    .addComponent(residenciaTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidadLBL)
                    .addComponent(nacionalidadTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instrumentoLBL)
                    .addComponent(instrumentoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverBTN)
                    .addComponent(insertarBTN))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBTNActionPerformed
        try {

            // Obtención de datos del formulario
            String codBandaStr = CodBandaTXT.getText().trim();
            String nombre = nombreTXT.getText().trim();
            String fecha = fechaTXT.getText().trim();
            String residencia = residenciaTXT.getText().trim();
            String nacionalidad = nacionalidadTXT.getText().trim();
            String instrumento = instrumentoTXT.getText().trim();

            // Validación del código de banda
            // Variable nullable
            Integer codBanda = null;

            // Si el campo no está vacío se valida
            if (!codBandaStr.isEmpty()) {

                // El código debe ser numérico
                if (!codBandaStr.matches("-?\\d+")) {
                    throw new Excepciones("El codigo de la banda debe ser numerico.");
                }

                codBanda = Integer.parseInt(codBandaStr);

                // El código no puede ser negativo
                if (codBanda < 0) {
                    throw new Excepciones("El codigo no puede ser negativo.");
                }

                // Comprobación de existencia de la banda
                if (!utils.Util_Clases.existeBandaCodigo(codBanda)) {
                    JOptionPane.showMessageDialog(null, "No existe una banda con ese codigo.");
                    return;
                }
            }

            // Validación del nombre
            // El nombre no puede estar vacío ni contener el texto por defecto
            if (nombre.isEmpty() || nombre.equalsIgnoreCase("Nombre")) {
                throw new Excepciones("Ingrese un nombre valido.");
            }

            // Comprobación de músico duplicado
            if (Sql_Musico.existeMusicoPorNombre(nombre)) {

                JOptionPane.showMessageDialog(null, "Ya existe un músico con ese nombre");
                return;
            }

            // Validación de fecha
            // La fecha no puede estar vacía ni contener el texto por defecto
            if (fecha.isEmpty() || fecha.equalsIgnoreCase("YYYY/MM/DD")) {
                throw new Excepciones("Ingrese una fecha valida.");
            }

            // Validación del formato de fecha
            if (!fecha.matches("\\d{4}/\\d{1,2}/\\d{1,2}")) {
                throw new Excepciones("La fecha debe tener formato YYYY/M/D.");
            }

            // Validación de residencia
            // La residencia no puede estar vacía ni contener el texto por defecto
            if (residencia.isEmpty() || residencia.equalsIgnoreCase("Residencia")) {
                throw new Excepciones("Ingrese una residencia valida.");
            }

            // Validación de nacionalidad
            // La nacionalidad no puede estar vacía ni contener el texto por defecto
            if (nacionalidad.isEmpty() || nacionalidad.equalsIgnoreCase("Nacionalidad")) {
                throw new Excepciones("Ingrese una nacionalidad valida.");
            }

            // Validación del instrumento
            // El instrumento no puede estar vacío ni contener el texto por defecto
            if (instrumento.isEmpty() || instrumento.equalsIgnoreCase("Instrumento")) {
                throw new Excepciones("Ingrese un instrumento valido.");
            }

            // Conversión de fecha
            // Se define el formato esperado
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy/M/d");

            LocalDate fechaNacimiento;

            try {

                // Conversión de String a LocalDate
                fechaNacimiento = LocalDate.parse(fecha, formato);

            } catch (Exception e) {

                throw new Excepciones("La fecha introducida no es valida.");
            }

            // Obtención de fecha actual
            LocalDate fechaActual = LocalDate.now();

            // Cálculo de edad
            int edad = fechaActual.getYear() - fechaNacimiento.getYear();

            // Ajuste si todavía no cumplió años este año
            if (fechaActual.getMonthValue() < fechaNacimiento.getMonthValue()
                    || (fechaActual.getMonthValue() == fechaNacimiento.getMonthValue()
                    && fechaActual.getDayOfMonth() < fechaNacimiento.getDayOfMonth())) {

                edad--;
            }

            // Validación de edad mínima
            if (edad < 16) {

                throw new Excepciones("El músico debe tener al menos 16 años.");
            }

            // Creación del objeto Musico
            Musico musico = new Musico(
                    codBanda,
                    nombre,
                    fecha,
                    residencia,
                    nacionalidad,
                    instrumento
            );

            // Inserción en base de datos
            Sql_Musico.insertar(musico);

            // Guardado en fichero TXT
            Contenedor_Musico.guardarMusicoTXT(musico);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "Músico insertado correctamente");

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_insertarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musico_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musico_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musico_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musico_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musico_Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodBandaTXT;
    private javax.swing.JLabel codigoLBL;
    private javax.swing.JLabel fechaLBL;
    private javax.swing.JTextField fechaTXT;
    private javax.swing.JButton insertarBTN;
    private javax.swing.JLabel instrumentoLBL;
    private javax.swing.JTextField instrumentoTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nacionalidadLBL;
    private javax.swing.JTextField nacionalidadTXT;
    private javax.swing.JLabel nombreLBL;
    private javax.swing.JTextField nombreTXT;
    private javax.swing.JLabel residenciaLBL;
    private javax.swing.JTextField residenciaTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
