/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Musico;

import services.Sql.Musico.Sql_Musico;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isard
 */
public class Musico_MostrarCodigo extends javax.swing.JFrame {

    /**
     * Creates new form Musico_MostrarCodigo
     */
    public Musico_MostrarCodigo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLBL = new javax.swing.JLabel();
        codigoTXT = new javax.swing.JTextField();
        buscarBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCodigoTBL = new javax.swing.JTable();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoLBL.setText("Introduce el codigo del músico");

        codigoTXT.setText("-1");

        buscarBTN.setText("Buscar");
        buscarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBTNActionPerformed(evt);
            }
        });

        tablaCodigoTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Codigo de la banda", "Nombre", "Fecha de nacimiento", "Residencia", "Nacionalidad", "Instrumento"
            }
        ));
        jScrollPane1.setViewportView(tablaCodigoTBL);

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(codigoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(volverBTN)
                .addGap(194, 194, 194)
                .addComponent(buscarBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLBL)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarBTN)
                    .addComponent(volverBTN))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBTNActionPerformed
        try {

            // Se crea el modelo de la tabla con los nombres de las columnas
            DefaultTableModel modelo = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{
                        "Codigo", "Codigo de la banda", "Nombre", "Fecha de nacimiento",
                        "Residencia", "Nacionalidad", "Instrumento"
                    }
            );

            // Se obtiene el código introducido por el usuario
            String textoCodigo = codigoTXT.getText().trim();

            // Validación: el campo no puede estar vacío
            if (textoCodigo.isEmpty()) {

                throw new Excepciones("Ingrese un código.");
            }

            // Conversión del código a entero
            int codigo = Integer.parseInt(textoCodigo);

            // Validación: el código no puede ser negativo
            if (codigo < 0) {

                throw new Excepciones("El código no puede ser negativo");
            }

            // Verificar si existe un músico con ese código
            if (!utils.Util_Clases.existeMusicoPorCodigo(codigo)) {

                throw new Excepciones("No existe un músico con ese código");
            }

            // Se asigna el modelo a la tabla
            tablaCodigoTBL.setModel(modelo);

            // Consulta de músicos por código en la base de datos
            String[][] matrizMostrar = Sql_Musico.consultarPorCodigo(codigo);

            // Validación: la matriz no puede ser null ni estar vacía
            if (matrizMostrar == null || matrizMostrar.length == 0) {

                throw new Excepciones("No se encontraron músicos con ese código");
            }

            // Variable para comprobar si existe al menos un dato válido
            boolean existeDatoReal = false;

            // Recorrido de la matriz obtenida
            for (int i = 0; i < matrizMostrar.length; i++) {

                // Validación de fila válida
                if (matrizMostrar[i] == null || matrizMostrar[i].length < 7) {

                    continue;
                }

                // Indica que existe al menos un dato válido
                existeDatoReal = true;

                // Añadir fila al modelo de la tabla
                modelo.addRow(new Object[]{
                    matrizMostrar[i][0],
                    matrizMostrar[i][1],
                    matrizMostrar[i][2],
                    matrizMostrar[i][3],
                    matrizMostrar[i][4],
                    matrizMostrar[i][5],
                    matrizMostrar[i][6]
                });
            }

            // Validación: si no existe ninguna fila válida
            if (!existeDatoReal) {

                throw new Excepciones("No existen músicos válidos con ese código.");
            }

        } catch (NumberFormatException e) {

            // Error cuando el código no es numérico
            JOptionPane.showMessageDialog(
                    null,
                    "Debes introducir un número válido"
            );

        } catch (Excepciones e) {

            // Error de validación personalizada
            JOptionPane.showMessageDialog(
                    null,
                    e.getMessage()
            );

        } catch (Exception e) {

            // Captura cualquier error inesperado
            JOptionPane.showMessageDialog(
                    null,
                    "Error inesperado: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_buscarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musico_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musico_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musico_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musico_MostrarCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musico_MostrarCodigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarBTN;
    private javax.swing.JLabel codigoLBL;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCodigoTBL;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
