/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Cancion;

import modelo.Cancion;
import services.Contenedor_tablas.Contenedor_Cancion;
import services.Sql.Cancion.Sql_Cancion;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import utils.Util_Tiempo;

/**
 *
 * @author isard
 */
public class Cancion_Insertar extends javax.swing.JFrame {

    /**
     * Creates new form Cancion_Insertar
     */
    public Cancion_Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        albumCodigoLBL = new javax.swing.JLabel();
        posicionLBL = new javax.swing.JLabel();
        tituloLBL = new javax.swing.JLabel();
        compositorLBL = new javax.swing.JLabel();
        duracionLBL = new javax.swing.JLabel();
        insertarBTN = new javax.swing.JButton();
        codigoAlbumTXT = new javax.swing.JTextField();
        posicionTXT = new javax.swing.JTextField();
        tituloTXT = new javax.swing.JTextField();
        compositorTXT = new javax.swing.JTextField();
        duracionTXT = new javax.swing.JTextField();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Introduce los datos");

        albumCodigoLBL.setText("Codigo del album");

        posicionLBL.setText("Posicion");

        tituloLBL.setText("Titulo");

        compositorLBL.setText("Compositor");

        duracionLBL.setText("Duracion");

        insertarBTN.setText("Insertar");
        insertarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBTNActionPerformed(evt);
            }
        });

        codigoAlbumTXT.setText("-1");

        posicionTXT.setText("-1");

        tituloTXT.setText("Titulo");

        compositorTXT.setText("Compositor");

        duracionTXT.setText("MM:SS");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(posicionLBL)
                    .addComponent(albumCodigoLBL)
                    .addComponent(tituloLBL)
                    .addComponent(compositorLBL)
                    .addComponent(duracionLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoAlbumTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compositorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(38, 38, 38)
                .addComponent(insertarBTN)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumCodigoLBL)
                    .addComponent(codigoAlbumTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicionLBL)
                    .addComponent(posicionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLBL)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compositorLBL)
                    .addComponent(compositorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracionLBL)
                    .addComponent(duracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertarBTN)
                    .addComponent(volverBTN))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBTNActionPerformed

        try {

            // Obtención de datos del formulario
            String codigoAlbumStr = codigoAlbumTXT.getText().trim();
            String posicionStr = posicionTXT.getText().trim();
            String titulo = tituloTXT.getText().trim();
            String compositor = compositorTXT.getText().trim();
            String duracion = duracionTXT.getText().trim();

            // Validación del código del álbum
            // El código del álbum no puede estar vacío
            if (codigoAlbumStr.isEmpty()) {
                throw new Excepciones("Ingrese el codigo del album.");
            }

            // El código del álbum debe ser numérico
            if (!codigoAlbumStr.matches("\\d+")) {
                throw new Excepciones("El codigo del album debe ser numerico.");
            }

            int codigoAlbum = Integer.parseInt(codigoAlbumStr);

            // Comprobación de existencia del álbum en la base de datos
            if (!utils.Util_Clases.existeAlbumCodigo(codigoAlbum)) {
                throw new Excepciones("No existe un album con ese codigo.");
            }

            // Validación de la posición
            // La posición no puede estar vacía
            if (posicionStr.isEmpty()) {
                throw new Excepciones("Ingrese la posicion de la cancion.");
            }

            // La posición debe ser numérica
            if (!posicionStr.matches("\\d+")) {
                throw new Excepciones("La posicion debe ser numerica.");
            }

            int posicion = Integer.parseInt(posicionStr);

            // La posición debe ser mayor que 0
            if (posicion <= 0) {
                throw new Excepciones("La posicion debe ser mayor que 0.");
            }

            // Validación de posición repetida
            if (Sql_Cancion.buscarPorAlbumYPosicion(
                    codigoAlbum,
                    posicion) != null) {

                throw new Excepciones(
                        "Ya existe una canción en esa posición del álbum."
                );
            }

            // Validación del título
            // El título no puede estar vacío ni contener el texto por defecto
            if (titulo.isEmpty() || titulo.equals("Titulo")) {
                throw new Excepciones("Ingrese un titulo valido.");
            }

            // Validación del compositor
            // El compositor no puede estar vacío ni contener el texto por defecto
            if (compositor.isEmpty() || compositor.equals("Compositor")) {
                throw new Excepciones("Ingrese un compositor valido.");
            }

            /// Validación de la duración
            // La duración no puede estar vacía ni contener el texto por defecto
            if (duracion.isEmpty() || duracion.equals("MM:SS")) {
                throw new Excepciones("Ingrese una duracion valida.");
            }

            // La duración debe tener formato MM:SS 
            if (!duracion.matches("\\d{2}(:\\d{2})?")) {
                throw new Excepciones("La duracion debe tener formato MM:SS ");
            }

            // Separación de partes
            String[] partesDuracion = duracion.split(":");

            int segundos;

            // Validación de segundos
            if (partesDuracion.length == 2) {

                // MM:SS
                segundos = Integer.parseInt(partesDuracion[1]);

            }

            // Normalización del tiempo
            duracion = Util_Tiempo.normalizarDuracion(duracion);

            // Separación de minutos y segundos normalizados
            String[] tiempoNormalizado = duracion.split(":");

            int minutosFinal = Integer.parseInt(tiempoNormalizado[0]);
            int segundosFinal = Integer.parseInt(tiempoNormalizado[1]);

            // El tiempo no puede ser 00:00
            if (minutosFinal == 0 && segundosFinal == 0) {
                throw new Excepciones(
                        "La duración no puede ser 00:00."
                );
            }

            // Validación máxima de duración
            if (minutosFinal > 15 || (minutosFinal == 15 && segundosFinal > 0)) {
                throw new Excepciones(
                        "La duración no puede superar los 15 minutos."
                );
            }

            // Creación del objeto Cancion
            Cancion cancion = new Cancion(
                    codigoAlbum,
                    posicion,
                    titulo,
                    compositor,
                    duracion
            );

            // Inserción en base de datos
            Sql_Cancion.insertar(cancion);

            // Guardado en fichero TXT
            Contenedor_Cancion.guardarCancionTXT(cancion);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "Cancion insertada correctamente");

        } catch (NumberFormatException e) {

            // Error cuando los valores numéricos son inválidos
            JOptionPane.showMessageDialog(null, "Codigo de album y posicion deben ser numeros validos");

        } catch (Excepciones e) {

            // Error controlado por validaciones
            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            // Error inesperado del sistema
            JOptionPane.showMessageDialog(null, "Error inesperado: " + e.getMessage());
        }

    }//GEN-LAST:event_insertarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancion_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancion_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancion_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancion_Insertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancion_Insertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel albumCodigoLBL;
    private javax.swing.JTextField codigoAlbumTXT;
    private javax.swing.JLabel compositorLBL;
    private javax.swing.JTextField compositorTXT;
    private javax.swing.JLabel duracionLBL;
    private javax.swing.JTextField duracionTXT;
    private javax.swing.JButton insertarBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel posicionLBL;
    private javax.swing.JTextField posicionTXT;
    private javax.swing.JLabel tituloLBL;
    private javax.swing.JTextField tituloTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
