/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Cancion;

import modelo.Cancion;
import services.Sql.Cancion.Sql_Cancion;
import excepciones.Excepciones;
import javax.swing.JOptionPane;
import utils.Util_Tiempo;

/**
 *
 * @author isard
 */
public class Cancion_Actualizar extends javax.swing.JFrame {

    /**
     * Creates new form Cancion_Actualizar
     */
    public Cancion_Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoLBL = new javax.swing.JLabel();
        actualizarBTN = new javax.swing.JButton();
        albumLBL = new javax.swing.JLabel();
        posicionLBL = new javax.swing.JLabel();
        tituloLBL = new javax.swing.JLabel();
        compositorLBL = new javax.swing.JLabel();
        duracionLBL = new javax.swing.JLabel();
        codigoLBL = new javax.swing.JLabel();
        albumTXT = new javax.swing.JTextField();
        posicionTXT = new javax.swing.JTextField();
        tituloTXT = new javax.swing.JTextField();
        compositorTXT = new javax.swing.JTextField();
        duracionTXT = new javax.swing.JTextField();
        codigoTXT = new javax.swing.JTextField();
        volverBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoLBL.setText("Introduce los datos");

        actualizarBTN.setText("Actualizar");
        actualizarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarBTNActionPerformed(evt);
            }
        });

        albumLBL.setText("Codigo del album");

        posicionLBL.setText("Poscicion");

        tituloLBL.setText("Titulo");

        compositorLBL.setText("Compsitor");

        duracionLBL.setText("Duracion");

        codigoLBL.setText("Codigo");

        albumTXT.setText("-1");

        posicionTXT.setText("-1");

        tituloTXT.setText("Titulo");

        compositorTXT.setText("Compositor");

        duracionTXT.setText("MM:SS");

        codigoTXT.setText("-1");

        volverBTN.setText("Volver");
        volverBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(posicionLBL)
                    .addComponent(albumLBL)
                    .addComponent(tituloLBL)
                    .addComponent(compositorLBL)
                    .addComponent(duracionLBL)
                    .addComponent(codigoLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(albumTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compositorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(textoLBL)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBTN)
                .addGap(37, 37, 37)
                .addComponent(actualizarBTN)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoLBL)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(albumLBL)
                    .addComponent(albumTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicionLBL)
                    .addComponent(posicionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLBL)
                    .addComponent(tituloTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compositorLBL)
                    .addComponent(compositorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracionLBL)
                    .addComponent(duracionTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLBL)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarBTN)
                    .addComponent(volverBTN))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarBTNActionPerformed
        try {

            // Obtención de datos del formulario
            String codigoStr = codigoTXT.getText().trim();
            String albumStr = albumTXT.getText().trim();
            String posicionStr = posicionTXT.getText().trim();
            String titulo = tituloTXT.getText().trim();
            String compositor = compositorTXT.getText().trim();
            String duracion = duracionTXT.getText().trim();

            // Validación del código de la canción
            // El código no puede estar vacío ni ser inválido
            if (codigoStr.isEmpty() || !codigoStr.matches("\\d+")) {
                throw new Excepciones("Ingrese un código de canción válido.");
            }

            int codigo = Integer.parseInt(codigoStr);

            // Validación del álbum
            // El código del álbum no puede estar vacío ni ser inválido
            if (albumStr.isEmpty() || !albumStr.matches("\\d+")) {
                throw new Excepciones("Ingrese un código de álbum válido.");
            }

            int album = Integer.parseInt(albumStr);

            // Validación de la posición
            // La posición no puede estar vacía ni ser negativa
            if (posicionStr.isEmpty() || !posicionStr.matches("\\d+")) {
                throw new Excepciones("Ingrese una posición válida.");
            }

            int posicion = Integer.parseInt(posicionStr);

            // La posición debe ser mayor que 0
            if (posicion <= 0) {
                throw new Excepciones("La posicion debe ser mayor que 0.");
            }

            // Validación de posición repetida
            if (Sql_Cancion.buscarPorAlbumYPosicion(
                    album,
                    posicion) != null) {

                throw new Excepciones(
                        "Ya existe una canción en esa posición del álbum."
                );
            }

            // Validación del título
            // El título no puede estar vacío ni contener texto por defecto
            if (titulo.isEmpty() || titulo.equals("Titulo")) {
                throw new Excepciones("Ingrese un título válido.");
            }

            // Validación del compositor
            // El compositor no puede estar vacío ni contener texto por defecto
            if (compositor.isEmpty() || compositor.equals("Compositor")) {
                throw new Excepciones("Ingrese un compositor válido.");
            }

            /// Validación de la duración
            // La duración no puede estar vacía ni contener el texto por defecto
            if (duracion.isEmpty() || duracion.equals("MM:SS")) {
                throw new Excepciones("Ingrese una duracion valida.");
            }

            // La duración debe tener formato MM:SS 
            if (!duracion.matches("\\d{2}(:\\d{2})?")) {
                throw new Excepciones("La duracion debe tener formato MM:SS ");
            }

            // Separación de partes
            String[] partesDuracion = duracion.split(":");

            int segundos;

            // Validación de segundos
            if (partesDuracion.length == 2) {

                // MM:SS
                segundos = Integer.parseInt(partesDuracion[1]);

            }

            // Normalización del tiempo
            duracion = Util_Tiempo.normalizarDuracion(duracion);

            // Separación de minutos y segundos normalizados
            String[] tiempoNormalizado = duracion.split(":");

            int minutosFinal = Integer.parseInt(tiempoNormalizado[0]);
            int segundosFinal = Integer.parseInt(tiempoNormalizado[1]);

            // El tiempo no puede ser 00:00
            if (minutosFinal == 0 && segundosFinal == 0) {
                throw new Excepciones(
                        "La duración no puede ser 00:00."
                );
            }

            // Validación máxima de duración
            if (minutosFinal > 15 || (minutosFinal == 15 && segundosFinal > 0)) {
                throw new Excepciones(
                        "La duración no puede superar los 15 minutos."
                );
            }

            // Comprobación de existencia de la canción
            Cancion cancionExistente = Sql_Cancion.buscarPorCodigo(codigo);

            if (cancionExistente == null) {
                throw new Excepciones("La canción no existe.");
            }

            // Comprobación de existencia del álbum
            if (!utils.Util_Clases.existeAlbumCodigo(album)) {
                throw new Excepciones("El álbum no existe.");
            }

            // Comprobación de conflicto de posición
            Cancion conflicto = Sql_Cancion.buscarPorAlbumYPosicion(album, posicion);

            if (conflicto != null && conflicto.getCodigo() != codigo) {
                throw new Excepciones("La posición ya está ocupada en este álbum.");
            }

            // Creación del objeto Cancion
            Cancion cancion = new Cancion(
                    album,
                    posicion,
                    titulo,
                    compositor,
                    duracion
            );

            // Actualización en base de datos
            Sql_Cancion.update(cancion, codigo);

            // Mensaje de éxito
            JOptionPane.showMessageDialog(null, "Canción actualizada correctamente.");

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null,
                    "Los códigos y la posición deben ser numéricos.");

        } catch (Excepciones e) {

            JOptionPane.showMessageDialog(null, e.getMessage());

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,
                    "Error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_actualizarBTNActionPerformed

    private void volverBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_volverBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancion_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancion_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancion_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancion_Actualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancion_Actualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarBTN;
    private javax.swing.JLabel albumLBL;
    private javax.swing.JTextField albumTXT;
    private javax.swing.JLabel codigoLBL;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JLabel compositorLBL;
    private javax.swing.JTextField compositorTXT;
    private javax.swing.JLabel duracionLBL;
    private javax.swing.JTextField duracionTXT;
    private javax.swing.JLabel posicionLBL;
    private javax.swing.JTextField posicionTXT;
    private javax.swing.JLabel textoLBL;
    private javax.swing.JLabel tituloLBL;
    private javax.swing.JTextField tituloTXT;
    private javax.swing.JButton volverBTN;
    // End of variables declaration//GEN-END:variables
}
